-- ---------------------------------------------------------------------------
-- Meshes, materials, and the acceleration structure.
--
-- Geometry lives in tables.  A scene is a set of meshes, each a bag of
-- triangles pointing at a material; changing what a mesh is made of is an
-- INSERT, and changing how it looks is an UPDATE of one foreign key.
--
-- The shapes of the queries here were chosen by measurement, not taste, and
-- two results drove every decision:
--
--   * Intersection must be ONE set-based join over every live ray, not a
--     scalar function called per ray.  A correlated per-ray subquery over the
--     same geometry measured 1097 ms where the flat join measured 388 ms --
--     the per-ray rescan setup costs more than the arithmetic it performs.
--
--   * A ray must carry its inverse direction as a real column.  Computing it
--     in a LATERAL is not enough: the planner pulls a single-row Result up
--     into the join filter and then re-evaluates the whole expression at each
--     of the twelve places the slab test mentions it.
--
-- Both are the same lesson the tracer already learned once -- a SQL function
-- body is macro-expanded into its caller -- arriving in a new disguise.
-- ---------------------------------------------------------------------------

-- Material kinds.  These drive every branch in the transport code, which no
-- longer knows the names of any particular object in the scene.
CREATE FUNCTION mat_diffuse() RETURNS int AS $$ SELECT 0 $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;
CREATE FUNCTION mat_metal()   RETURNS int AS $$ SELECT 1 $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;
CREATE FUNCTION mat_glass()   RETURNS int AS $$ SELECT 2 $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE TABLE material (
  mat_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text   NOT NULL UNIQUE,
  kind    int    NOT NULL CHECK (kind BETWEEN 0 AND 2),
  albedo  vec3   NOT NULL DEFAULT ROW(0.8, 0.8, 0.8)::vec3,
  -- Second checker colour and cell size.  checker = 0 means a plain surface;
  -- the pattern is procedural rather than a texture because a texture would
  -- need UVs, and nothing else here does.
  albedo2 vec3   NOT NULL DEFAULT ROW(0.8, 0.8, 0.8)::vec3,
  checker float8 NOT NULL DEFAULT 0.0,
  tint    vec3   NOT NULL DEFAULT ROW(1, 1, 1)::vec3,   -- metal F0
  -- Index of refraction per channel.  Three different values is what splits
  -- white light: the dispersion is a property of the material, not of the
  -- tracer, so a second glass with a different spread is just another row.
  ior     vec3   NOT NULL DEFAULT ROW(1.5, 1.5, 1.5)::vec3,
  absorb  vec3   NOT NULL DEFAULT ROW(0, 0, 0)::vec3,   -- Beer-Lambert
  spec_e  float8 NOT NULL DEFAULT 260.0,                -- specular exponent
  spec_k  float8 NOT NULL DEFAULT 2.0,                  -- specular strength
  f0      float8 NOT NULL DEFAULT 0.045,                -- reflectance head-on
  kr_max  float8 NOT NULL DEFAULT 1.0                   -- reflectance ceiling
);

CREATE TABLE mesh (
  mesh_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text NOT NULL UNIQUE,
  mat_id  int  NOT NULL REFERENCES material(mat_id)
);

-- Vertex normals are nullable: a mesh with none is shaded flat off its
-- geometric normal, which is what a box wants and a sphere does not.
--
-- The trailing float8 columns are the same three vertices in the form the
-- intersection test actually wants, and they are the single largest
-- optimisation in the engine.  `vec3` is a composite type, so every `(t.a).x`
-- in an expression is a FieldSelect that re-reads the embedded tuple header
-- and walks to the field -- about 10 ns each, against roughly 1 ns for a
-- plain float8 Var.  The triangle test mentions its arguments some sixty
-- times once it is inlined, and the slab test mentions its four vectors
-- thirty-six times.  Measured over the 460304 candidate pairs of a 240x160
-- frame, the identical arithmetic reading composites costs 387 ns per box
-- test and reading flat columns 106 ns; for triangles it is 1.6 us against
-- 0.32 us.  The vectors stay as `vec3` because the rest of the engine is
-- written in vector algebra; these are a derived, generated view of them, so
-- they cannot drift.
--
-- e1 / e2 / gn are precomputed as well: the edges and the (unnormalised)
-- facet normal are ray-independent, and gn is what turns Moller-Trumbore's
-- determinant into a single dot product -- see tri_hit below.
--
-- The last six are the triangle's own bounding box, and they are the bottom
-- level of the hierarchy rather than an optimisation of the leaf above it.  A
-- slab test costs about a third of a Moller-Trumbore, so testing a triangle's
-- box before intersecting it pays as soon as that box rejects more than a
-- third of what reaches it.  It rejects far more: a leaf is a run of Morton-
-- ordered triangles, so it is compact but not tight, and most of what a leaf
-- admits misses every triangle in it.  Unlike the boxes on bvh_node and
-- mesh_box these are stored flat only, with no `vec3` beside them -- those two
-- mirror a stored vector, whereas this one has no authority to mirror.  It is
-- derived from the vertices, and only the slab test ever reads it.
CREATE TABLE tri (
  tri_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesh_id int  NOT NULL REFERENCES mesh(mesh_id) ON DELETE CASCADE,
  a vec3 NOT NULL, b vec3 NOT NULL, c vec3 NOT NULL,
  na vec3, nb vec3, nc vec3,
  cl int,                      -- BVH leaf, assigned by scene_reindex()
  ax  float8 GENERATED ALWAYS AS ((a).x) STORED,
  ay  float8 GENERATED ALWAYS AS ((a).y) STORED,
  az  float8 GENERATED ALWAYS AS ((a).z) STORED,
  e1x float8 GENERATED ALWAYS AS ((b).x - (a).x) STORED,
  e1y float8 GENERATED ALWAYS AS ((b).y - (a).y) STORED,
  e1z float8 GENERATED ALWAYS AS ((b).z - (a).z) STORED,
  e2x float8 GENERATED ALWAYS AS ((c).x - (a).x) STORED,
  e2y float8 GENERATED ALWAYS AS ((c).y - (a).y) STORED,
  e2z float8 GENERATED ALWAYS AS ((c).z - (a).z) STORED,
  gnx float8 GENERATED ALWAYS AS (((b).y - (a).y) * ((c).z - (a).z)
                                - ((b).z - (a).z) * ((c).y - (a).y)) STORED,
  gny float8 GENERATED ALWAYS AS (((b).z - (a).z) * ((c).x - (a).x)
                                - ((b).x - (a).x) * ((c).z - (a).z)) STORED,
  gnz float8 GENERATED ALWAYS AS (((b).x - (a).x) * ((c).y - (a).y)
                                - ((b).y - (a).y) * ((c).x - (a).x)) STORED,
  lox float8 GENERATED ALWAYS AS (least((a).x, (b).x, (c).x)) STORED,
  loy float8 GENERATED ALWAYS AS (least((a).y, (b).y, (c).y)) STORED,
  loz float8 GENERATED ALWAYS AS (least((a).z, (b).z, (c).z)) STORED,
  hix float8 GENERATED ALWAYS AS (greatest((a).x, (b).x, (c).x)) STORED,
  hiy float8 GENERATED ALWAYS AS (greatest((a).y, (b).y, (c).y)) STORED,
  hiz float8 GENERATED ALWAYS AS (greatest((a).z, (b).z, (c).z)) STORED
);
CREATE INDEX tri_cl_idx   ON tri (cl);
CREATE INDEX tri_mesh_idx ON tri (mesh_id);

-- Two levels of bounding volume above the triangles: one box per mesh, one per
-- leaf cluster.  Both carry the same flat mirror of their corners, for the
-- same reason.
CREATE TABLE bvh_node (
  cl      int PRIMARY KEY,
  mesh_id int  NOT NULL REFERENCES mesh(mesh_id) ON DELETE CASCADE,
  lo vec3 NOT NULL, hi vec3 NOT NULL,
  lox float8 GENERATED ALWAYS AS ((lo).x) STORED,
  loy float8 GENERATED ALWAYS AS ((lo).y) STORED,
  loz float8 GENERATED ALWAYS AS ((lo).z) STORED,
  hix float8 GENERATED ALWAYS AS ((hi).x) STORED,
  hiy float8 GENERATED ALWAYS AS ((hi).y) STORED,
  hiz float8 GENERATED ALWAYS AS ((hi).z) STORED
);
CREATE TABLE mesh_box (
  mesh_id int PRIMARY KEY REFERENCES mesh(mesh_id) ON DELETE CASCADE,
  lo vec3 NOT NULL, hi vec3 NOT NULL,
  lox float8 GENERATED ALWAYS AS ((lo).x) STORED,
  loy float8 GENERATED ALWAYS AS ((lo).y) STORED,
  loz float8 GENERATED ALWAYS AS ((lo).z) STORED,
  hix float8 GENERATED ALWAYS AS ((hi).x) STORED,
  hiy float8 GENERATED ALWAYS AS ((hi).y) STORED,
  hiz float8 GENERATED ALWAYS AS ((hi).z) STORED
);

-- ---------------------------------------------------------------------------
-- Ray/geometry tests.
-- ---------------------------------------------------------------------------

-- Guard against an exactly axis-parallel direction component.  Substituting a
-- tiny value rather than NULL keeps the slab arithmetic branch-free: the
-- resulting huge interval either swallows the axis or inverts into a miss,
-- which is the right answer in both cases.
CREATE FUNCTION nz(v float8) RETURNS float8
  AS $$ SELECT CASE WHEN abs(v) < 1e-12 THEN 1e-12 ELSE v END $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION v3_inv(d vec3) RETURNS vec3
  AS $$ SELECT ROW(1.0 / nz((d).x), 1.0 / nz((d).y), 1.0 / nz((d).z))::vec3 $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Slab test against an AABB, given the ray's precomputed inverse direction.
--
-- Deliberately FROM-less so it inlines, even though that makes the planner
-- evaluate each of the six slab products twice -- once under least(), once
-- under greatest().  The duplicated arithmetic is cheaper than the call it
-- avoids: the same test written in PL/pgSQL with locals measured 782 ms
-- against this version's 415 ms over a million boxes.
--
-- Flat scalars rather than vec3, because inlining is exactly what makes the
-- composite form expensive: the body names its four vectors thirty-six times,
-- and each of those becomes a FieldSelect over an embedded tuple.  Over 3.7 M
-- slab tests the composite form measured 387 ns per test and this one 106 ns,
-- for bit-identical results.
CREATE FUNCTION box_hit(ox float8, oy float8, oz float8,
                        ivx float8, ivy float8, ivz float8,
                        lox float8, loy float8, loz float8,
                        hix float8, hiy float8, hiz float8) RETURNS boolean AS $$
  SELECT least(greatest((lox - ox) * ivx, (hix - ox) * ivx),
               greatest((loy - oy) * ivy, (hiy - oy) * ivy),
               greatest((loz - oz) * ivz, (hiz - oz) * ivz))
       >= greatest(least((lox - ox) * ivx, (hix - ox) * ivx),
                   least((loy - oy) * ivy, (hiy - oy) * ivy),
                   least((loz - oz) * ivz, (hiz - oz) * ivz),
                   1e-4)
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Vector spelling of the same test, for callers holding vec3s.  The renderer
-- does not use it; it exists so the geometry can be poked at from psql.
CREATE FUNCTION box_hit(o vec3, iv vec3, lo vec3, hi vec3) RETURNS boolean AS $$
  SELECT box_hit((o).x, (o).y, (o).z, (iv).x, (iv).y, (iv).z,
                 (lo).x, (lo).y, (lo).z, (hi).x, (hi).y, (hi).z)
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Moller-Trumbore, returning only the distance, over a triangle presented as
-- its first vertex, its two edges and its unnormalised facet normal -- all
-- three ray-independent and stored on `tri`.
--
-- Written that way the determinant collapses.  With gn = e1 x e2,
--
--     det  =  e1 . (d x e2)  =  -(d . gn)
--
-- so the one quantity every barycentric divides by is a plain dot product
-- rather than a cross product folded into a dot.  Writing w = a - o (which
-- flips the sign of det back out again):
--
--     D = d . gn      t = (w . gn) / D
--     u = (w . (d x e2)) / D          v = (d . (w x e1)) / D
--
-- and this is FROM-less SQL, so it inlines and pays no call at all.  That
-- inlining is why D is spelled out five times instead of being held in a
-- local: a repeated six-node dot product is cheaper than the 350 ns a
-- PL/pgSQL invocation costs before it executes a single statement.  It is the
-- same trade box_hit makes, and it holds much further up the size scale than
-- the old comment on box_hit assumed -- the whole of Moller-Trumbore fits
-- under it.  Over the 460304 candidate pairs of a 240x160 frame: 1.60 us per
-- test for the PL/pgSQL version, 0.32 us for this one, with identical
-- hit/miss classification and at most 2.5e-14 difference in t.
--
-- The tests are ordered by how much they reject, measured rather than
-- assumed: of those 460304 candidates 76% die on u, 15% on v, and only 1.2%
-- behind the ray -- so u goes first and the distance test goes last, even
-- though the distance is now the cheapest of the three to compute.
--
-- The barycentric coordinates are deliberately NOT returned -- they are
-- needed only for the one triangle a ray actually lands on, so recovering
-- them once per ray afterwards is far cheaper than returning them from every
-- test.
CREATE FUNCTION tri_hit(ox float8, oy float8, oz float8,
                        dx float8, dy float8, dz float8,
                        ax float8, ay float8, az float8,
                        e1x float8, e1y float8, e1z float8,
                        e2x float8, e2y float8, e2z float8,
                        gnx float8, gny float8, gnz float8) RETURNS float8 AS $$
  SELECT CASE
    -- ray parallel to the plane
    WHEN abs(dx*gnx + dy*gny + dz*gnz) < 1e-12 THEN NULL
    WHEN ((ax-ox)*(dy*e2z-dz*e2y) + (ay-oy)*(dz*e2x-dx*e2z)
        + (az-oz)*(dx*e2y-dy*e2x)) / (dx*gnx + dy*gny + dz*gnz)
         NOT BETWEEN 0.0 AND 1.0 THEN NULL
    WHEN (dx*((ay-oy)*e1z-(az-oz)*e1y) + dy*((az-oz)*e1x-(ax-ox)*e1z)
        + dz*((ax-ox)*e1y-(ay-oy)*e1x)) / (dx*gnx + dy*gny + dz*gnz)
         < 0.0 THEN NULL
    WHEN (((ax-ox)*(dy*e2z-dz*e2y) + (ay-oy)*(dz*e2x-dx*e2z)
         + (az-oz)*(dx*e2y-dy*e2x))
        + (dx*((ay-oy)*e1z-(az-oz)*e1y) + dy*((az-oz)*e1x-(ax-ox)*e1z)
         + dz*((ax-ox)*e1y-(ay-oy)*e1x))) / (dx*gnx + dy*gny + dz*gnz)
         > 1.0 THEN NULL
    WHEN ((ax-ox)*gnx + (ay-oy)*gny + (az-oz)*gnz)
       / (dx*gnx + dy*gny + dz*gnz) > 1e-4
    THEN ((ax-ox)*gnx + (ay-oy)*gny + (az-oz)*gnz)
       / (dx*gnx + dy*gny + dz*gnz)
    ELSE NULL
  END
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Vector spelling, for callers holding three vertices rather than a `tri`
-- row.  PL/pgSQL so that the edges and the facet normal are derived once
-- rather than at each of the sixty places the inlined body names them.
CREATE FUNCTION tri_hit(o vec3, d vec3, a vec3, b vec3, c vec3) RETURNS float8 AS $$
DECLARE
  e1 vec3 := b - a;
  e2 vec3 := c - a;
  gn vec3 := v3_cross(b - a, c - a);
BEGIN
  RETURN tri_hit((o).x, (o).y, (o).z, (d).x, (d).y, (d).z,
                 (a).x, (a).y, (a).z, (e1).x, (e1).y, (e1).z,
                 (e2).x, (e2).y, (e2).z, (gn).x, (gn).y, (gn).z);
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- Barycentric coordinates (u, v, w) of the point where the ray meets the
-- triangle's plane.  Called once per ray, for the winning triangle only --
-- but "once per ray" is still 200 000 times a frame, so it is the same
-- FROM-less flat kernel as tri_hit, over the same stored quantities.
CREATE FUNCTION tri_bary(ox float8, oy float8, oz float8,
                         dx float8, dy float8, dz float8,
                         ax float8, ay float8, az float8,
                         e1x float8, e1y float8, e1z float8,
                         e2x float8, e2y float8, e2z float8,
                         gnx float8, gny float8, gnz float8) RETURNS vec3 AS $$
  SELECT ROW(((ax-ox)*(dy*e2z-dz*e2y) + (ay-oy)*(dz*e2x-dx*e2z)
            + (az-oz)*(dx*e2y-dy*e2x)) / nz(dx*gnx + dy*gny + dz*gnz),
             (dx*((ay-oy)*e1z-(az-oz)*e1y) + dy*((az-oz)*e1x-(ax-ox)*e1z)
            + dz*((ax-ox)*e1y-(ay-oy)*e1x)) / nz(dx*gnx + dy*gny + dz*gnz),
             1.0
           - ((ax-ox)*(dy*e2z-dz*e2y) + (ay-oy)*(dz*e2x-dx*e2z)
            + (az-oz)*(dx*e2y-dy*e2x)) / nz(dx*gnx + dy*gny + dz*gnz)
           - (dx*((ay-oy)*e1z-(az-oz)*e1y) + dy*((az-oz)*e1x-(ax-ox)*e1z)
            + dz*((ax-ox)*e1y-(ay-oy)*e1x)) / nz(dx*gnx + dy*gny + dz*gnz))::vec3
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION tri_bary(o vec3, d vec3, a vec3, b vec3, c vec3) RETURNS vec3 AS $$
DECLARE
  e1 vec3 := b - a;
  e2 vec3 := c - a;
  gn vec3 := v3_cross(b - a, c - a);
BEGIN
  RETURN tri_bary((o).x, (o).y, (o).z, (d).x, (d).y, (d).z,
                  (a).x, (a).y, (a).z, (e1).x, (e1).y, (e1).z,
                  (e2).x, (e2).y, (e2).z, (gn).x, (gn).y, (gn).z);
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- Geometric (facet) normal, unit length.  Component form, because
-- `v3_unit(v3_cross(b - a, c - a))` hands v3_unit fifteen operators for a
-- parameter it names twelve times, which is over the inlining threshold and
-- turns the whole thing into a per-call executor run.
CREATE FUNCTION tri_normal(a vec3, b vec3, c vec3) RETURNS vec3
  AS $$ SELECT v3_unit(((b).y-(a).y) * ((c).z-(a).z) - ((b).z-(a).z) * ((c).y-(a).y),
                       ((b).z-(a).z) * ((c).x-(a).x) - ((b).x-(a).x) * ((c).z-(a).z),
                       ((b).x-(a).x) * ((c).y-(a).y) - ((b).y-(a).y) * ((c).x-(a).x)) $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Shading normal at barycentric (u, v): the interpolated vertex normals when
-- the mesh carries them, the facet normal when it does not.  Component form
-- again, and off the stored facet normal in the flat case.
CREATE FUNCTION tri_shading_normal(t tri, bc vec3) RETURNS vec3 AS $$
  SELECT CASE
    WHEN t.na IS NULL THEN v3_unit(t.gnx, t.gny, t.gnz)
    ELSE v3_unit((t.na).x * (bc).z + (t.nb).x * (bc).x + (t.nc).x * (bc).y,
                 (t.na).y * (bc).z + (t.nb).y * (bc).x + (t.nc).y * (bc).y,
                 (t.na).z * (bc).z + (t.nb).z * (bc).x + (t.nc).z * (bc).y)
  END $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- Nearest hit, as an aggregate.
--
-- Reducing millions of candidates to one row per ray with DISTINCT ON means
-- sorting every candidate; this picks the minimum in a single hash pass
-- instead.  It is the same trick as the vec3 sum aggregate: give the executor
-- a combine function and the reduction parallelises for free.
-- ---------------------------------------------------------------------------

CREATE TYPE cand AS (t float8, tri_id int);

-- What a ray found.  The normal is already flipped to face the incoming ray,
-- with `back` recording whether the geometric normal pointed away -- the
-- refraction code needs to know which side of a surface it is standing on.
-- `mat` is 0 for a miss, which is the only object identity left in the
-- tracer: everything else it needs to know arrives from the material row.
CREATE TYPE hit AS (
  t    float8,
  mat  int,
  p    vec3,
  n    vec3,
  back boolean
);

-- Rebuild a hit from flat columns.  The renderer stores its accumulated hits
-- as loose float8 because a nested composite pays a tuple header at every
-- level, but the shading functions want the record, so this is the seam
-- between the two representations.  Every parameter is named exactly once, so
-- it inlines whatever the arguments cost.
CREATE FUNCTION hit_of(t float8, mat int, px float8, py float8, pz float8,
                       nx float8, ny float8, nz float8, back boolean)
RETURNS hit
  AS $$ SELECT ROW(t, mat, ROW(px, py, pz)::vec3,
                   ROW(nx, ny, nz)::vec3, back)::hit $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Exact distance ties are resolved on tri_id, which is what makes this a
-- genuine minimum rather than "whichever arrived first".  A combine function
-- has to be commutative for a parallel aggregate to have a defined answer,
-- and without the tie-break this one is not: a Gather delivers candidates in
-- whatever order the workers finish, so a tie makes the whole frame depend on
-- scheduling.  Ties are not exotic -- both triangles of a quad face carry the
-- same first vertex and the same facet normal, so the distance to their
-- shared plane is computed from identical numbers and any ray crossing the
-- diagonal ties exactly.  Left unbroken, roughly 1% of the pixels of a
-- 120x80 frame moved from run to run.
CREATE FUNCTION cand_min(a cand, b cand) RETURNS cand AS $$
  SELECT CASE WHEN (b).t IS NULL THEN a
              WHEN (a).t IS NULL THEN b
              WHEN (b).t < (a).t THEN b
              WHEN (b).t > (a).t THEN a
              WHEN (b).tri_id < (a).tri_id THEN b
              ELSE a END
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE AGGREGATE nearest(cand) (
  SFUNC = cand_min, STYPE = cand, COMBINEFUNC = cand_min, PARALLEL = SAFE);

-- Assemble a hit record from the winning candidate.  Called once per ray
-- rather than once per candidate, which is what makes it affordable to
-- recover the barycentric coordinates here instead of returning them from
-- every triangle test.
--
-- `back` is decided by the GEOMETRIC normal even though the shading normal is
-- what gets returned: an interpolated normal near a silhouette can point the
-- wrong way relative to the facet, and refraction needs to know which side of
-- the surface it is really standing on.
CREATE FUNCTION make_hit(o vec3, d vec3, c cand, t tri, mat int) RETURNS hit AS $$
DECLARE
  gn vec3;
  bc vec3;
  sn vec3;
  bk boolean;
BEGIN
  IF (c).tri_id IS NULL THEN
    RETURN ROW(0.0, 0, o, -d, false)::hit;      -- miss: the ray sees the sky
  END IF;
  gn := v3_unit(t.gnx, t.gny, t.gnz);
  -- The barycentric coordinates go into a local before tri_shading_normal
  -- sees them, and that is not house style -- it is the whole cost of this
  -- function.  tri_shading_normal names its `bc` parameter three times, so
  -- passing the tri_bary call directly puts a PL/pgSQL invocation (procost
  -- 100, forty times the inlining threshold) in a multiply-used parameter,
  -- and PostgreSQL responds by not inlining tri_shading_normal at all: it
  -- becomes a real SQL function call, a full executor setup and run, once per
  -- ray.  Written this way `bc` is a Param, costs nothing to duplicate, and
  -- the body folds into the caller.  Measured over 38400 primary hits, the
  -- one-line difference is 1347 ms against 448 ms; the rest of this function
  -- takes it to 88 ms.  Nothing about the plan or the EXPLAIN output shows
  -- it -- only the timing does, and the arithmetic is identical to 6e-16.
  bc := tri_bary((o).x, (o).y, (o).z, (d).x, (d).y, (d).z,
                 t.ax, t.ay, t.az, t.e1x, t.e1y, t.e1z,
                 t.e2x, t.e2y, t.e2z, t.gnx, t.gny, t.gnz);
  sn := tri_shading_normal(t, bc);
  bk := v3_dot(d, gn) > 0.0;
  RETURN ROW((c).t, mat, o + d * (c).t,
             CASE WHEN bk THEN -sn ELSE sn END, bk)::hit;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- Building the BVH.
--
-- Two built levels only, because the number of join levels has to be written
-- into the query text -- a tree of arbitrary depth would need a recursive
-- descent per bounce, and the bounce loop is already the outer recursion.
-- Leaves are runs of Morton-ordered triangles, which keeps a leaf spatially
-- compact: grouping by insertion order instead produced boxes that spanned the
-- whole object and filtered nothing (measured slower than no BVH at all).
--
-- A third interior level -- groups of leaves, so a ray clearing a mesh box
-- need not test every leaf that mesh owns -- was built and measured, and is
-- deliberately absent.  Against the triangle box below it is a wash, worth a
-- few percent in one direction on the default scene and a few percent in the
-- other on the 2050-triangle torus, and only at a fan-out of four.
--
-- What settled it is how the fan-out fails.  Six leaves to a group, which
-- sounds every bit as reasonable as four, cost 38% on the torus.  The two plan
-- identically and report identical row counts at every node, because the work
-- is the slab tests at the leaf level -- (rays surviving the group) x fan --
-- and EXPLAIN counts only the rows that survive a filter, never the times it
-- ran.  The 38% appears nowhere but the clock.  A tuning knob that has to be
-- guessed per mesh, has no visible failure mode, and buys single digits when
-- guessed right is not worth a table and an index.
-- ---------------------------------------------------------------------------

-- Spread the low 10 bits of n so that two zero bits sit between each pair.
CREATE FUNCTION part1by2(n bigint) RETURNS bigint AS $$
DECLARE x bigint := n & 1023;
BEGIN
  x := (x | (x << 16)) &  50331903;
  x := (x | (x <<  8)) &  50393103;
  x := (x | (x <<  4)) &  51130563;
  x := (x | (x <<  2)) & 153391689;
  RETURN x;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION scene_reindex(p_leaf int DEFAULT NULL) RETURNS void AS $$
BEGIN
  -- Leaf size trades box tests against triangle tests.  The balance is not
  -- sqrt(n): a triangle test costs about three times a box test, so the
  -- optimum sits well below it.  The default was measured, not derived.
  --
  -- It was measured again when the triangle box arrived, on the theory that a
  -- cheaper way to reject a triangle should want different leaves, and halving
  -- it did look like a win: on the traced phases of a 240x160 frame, 4610 ms
  -- against 4740 on the default scene and 5270 against 5820 on the torus.
  --
  -- It is left alone anyway, because that result did not survive the machine
  -- changing power profile underneath it.  On a machine roughly twice as fast
  -- the same sweep put the minimum back up at 11, and the ordering of the two
  -- candidates reversed on the default scene.  A leaf size balances box tests
  -- against triangle tests, and that balance is a property of the machine as
  -- much as of the geometry -- so the honest default is the one that was
  -- already there, and p_leaf is how you tune it for yours.  The triangle box
  -- below is worth having either way: it measured 1.09x on the default scene
  -- and about 1.6x on the torus under both profiles.
  WITH cen AS (
    SELECT tri_id, mesh_id,
           ((a).x + (b).x + (c).x) / 3.0 AS cx,
           ((a).y + (b).y + (c).y) / 3.0 AS cy,
           ((a).z + (b).z + (c).z) / 3.0 AS cz
    FROM tri
  ), bnd AS (
    SELECT mesh_id, min(cx) mnx, max(cx) mxx, min(cy) mny,
           max(cy) mxy, min(cz) mnz, max(cz) mxz,
           -- sqrt(n)/3, measured: for the default scene's 1104-triangle ball
           -- that is 11, and a sweep over 4..40 put the minimum at 8-12
           -- (798 ms against 1380 ms for plain sqrt(n)).  Below it the leaf
           -- boxes themselves start costing more than the triangles they skip.
           coalesce(p_leaf, greatest(4, least(48,
                    ceil(sqrt(count(*)::float8) / 3.0)::int))) AS leaf
    FROM cen GROUP BY mesh_id
  ), code AS (
    SELECT c.tri_id, c.mesh_id, b.leaf,
           part1by2((1023.0 * (c.cx - b.mnx) / nz(b.mxx - b.mnx))::bigint)
        | (part1by2((1023.0 * (c.cy - b.mny) / nz(b.mxy - b.mny))::bigint) << 1)
        | (part1by2((1023.0 * (c.cz - b.mnz) / nz(b.mxz - b.mnz))::bigint) << 2) AS mo
    FROM cen c JOIN bnd b USING (mesh_id)
  ), grp AS (
    SELECT tri_id, mesh_id,
           ((row_number() OVER (PARTITION BY mesh_id ORDER BY mo, tri_id) - 1)
            / leaf)::int AS g
    FROM code
  )
  UPDATE tri SET cl = d.cl FROM (
    SELECT tri_id, dense_rank() OVER (ORDER BY mesh_id, g)::int AS cl FROM grp
  ) d WHERE tri.tri_id = d.tri_id;

  DELETE FROM bvh_node;
  INSERT INTO bvh_node (cl, mesh_id, lo, hi)
  SELECT cl, min(mesh_id),
         ROW(min((v).x), min((v).y), min((v).z))::vec3,
         ROW(max((v).x), max((v).y), max((v).z))::vec3
  FROM (SELECT cl, mesh_id, unnest(ARRAY[a, b, c]) AS v FROM tri) u
  GROUP BY cl;

  DELETE FROM mesh_box;
  INSERT INTO mesh_box (mesh_id, lo, hi)
  SELECT mesh_id,
         ROW(min((lo).x), min((lo).y), min((lo).z))::vec3,
         ROW(max((hi).x), max((hi).y), max((hi).z))::vec3
  FROM bvh_node GROUP BY mesh_id;

  ANALYZE tri;
  ANALYZE bvh_node;
  ANALYZE mesh_box;
END $$ LANGUAGE plpgsql;

-- Nearest hit for a single ray.
--
-- The renderer does NOT use this -- it intersects every live ray in one join,
-- because a call per ray is what made the first version slow.  This exists so
-- the geometry can be tested and poked at from psql, and so a bug in the BVH
-- can be caught by comparing it against a brute-force scan.
CREATE FUNCTION scene_hit(o vec3, d vec3) RETURNS hit AS $$
DECLARE
  iv   vec3 := v3_inv(d);
  bt   float8;
  bid  int;
  tr   tri;
  mid  int;
BEGIN
  -- Selected field by field rather than straight into a `cand` variable:
  -- SELECT ... INTO a composite target assigns the query's COLUMNS to the
  -- target's FIELDS, so a single composite-valued column would land in t.
  SELECT (q.c).t, (q.c).tri_id INTO bt, bid
  FROM (
    SELECT nearest(ROW(x.t, t.tri_id)::cand) AS c
    FROM mesh_box mb
         JOIN bvh_node n ON n.mesh_id = mb.mesh_id
         JOIN tri t      ON t.cl = n.cl
         CROSS JOIN LATERAL (
           SELECT tri_hit((o).x, (o).y, (o).z, (d).x, (d).y, (d).z,
                          t.ax, t.ay, t.az, t.e1x, t.e1y, t.e1z,
                          t.e2x, t.e2y, t.e2z, t.gnx, t.gny, t.gnz)
           OFFSET 0) AS x(t)
    WHERE box_hit((o).x, (o).y, (o).z, (iv).x, (iv).y, (iv).z,
                  mb.lox, mb.loy, mb.loz, mb.hix, mb.hiy, mb.hiz)
      AND box_hit((o).x, (o).y, (o).z, (iv).x, (iv).y, (iv).z,
                  n.lox, n.loy, n.loz, n.hix, n.hiy, n.hiz)
      AND box_hit((o).x, (o).y, (o).z, (iv).x, (iv).y, (iv).z,
                  t.lox, t.loy, t.loz, t.hix, t.hiy, t.hiz)
      AND x.t IS NOT NULL
  ) q;

  IF bid IS NULL THEN
    RETURN make_hit(o, d, NULL::cand, NULL::tri, 0);
  END IF;
  SELECT * INTO tr FROM tri WHERE tri_id = bid;
  SELECT ms.mat_id INTO mid FROM mesh ms WHERE ms.mesh_id = tr.mesh_id;
  RETURN make_hit(o, d, ROW(bt, bid)::cand, tr, mid);
END $$ LANGUAGE plpgsql STABLE PARALLEL SAFE;

-- The material a hit landed on, for callers holding only a hit record.
CREATE FUNCTION mat_of(h hit) RETURNS material AS $$
  SELECT * FROM material WHERE mat_id = (h).mat
$$ LANGUAGE sql STABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- Getting geometry in.
-- ---------------------------------------------------------------------------

-- Scale, then pitch about X, then yaw about Y, then translate.  Two angles
-- rather than a full matrix type: it is the least that can aim an arbitrary
-- mesh, and a 4x4 would need a type, an operator and an inverse-transpose for
-- the normals to earn its place.
CREATE FUNCTION v3_rot(p vec3, yaw float8, pitch float8) RETURNS vec3 AS $$
DECLARE
  y float8 := (p).y * cos(pitch) - (p).z * sin(pitch);
  z float8 := (p).y * sin(pitch) + (p).z * cos(pitch);
BEGIN
  RETURN ROW( (p).x * cos(yaw) + z * sin(yaw),
              y,
             -(p).x * sin(yaw) + z * cos(yaw))::vec3;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION v3_place(p vec3, s float8, yaw float8, at vec3,
                         pitch float8 DEFAULT 0.0) RETURNS vec3
  AS $$ SELECT v3_rot(p * s, yaw, pitch) + at $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION mesh_new(p_name text, p_material text) RETURNS int AS $$
DECLARE m int; mt int;
BEGIN
  SELECT mat_id INTO mt FROM material WHERE name = p_material;
  IF mt IS NULL THEN RAISE EXCEPTION 'no material named %', p_material; END IF;
  INSERT INTO mesh (name, mat_id) VALUES (p_name, mt) RETURNING mesh_id INTO m;
  RETURN m;
END $$ LANGUAGE plpgsql;

-- Assign a different material to an existing mesh.  This is the whole of
-- "selectable materials": geometry and appearance are separate rows.
CREATE FUNCTION mesh_set_material(p_mesh text, p_material text) RETURNS void AS $$
  UPDATE mesh SET mat_id = (SELECT mat_id FROM material WHERE name = p_material)
  WHERE name = p_mesh
$$ LANGUAGE sql;

-- Area-weighted vertex normals, averaged over every face meeting a vertex.
-- Vertices are matched by position, so a mesh loaded without normals comes
-- out smooth wherever it is geometrically closed and creased where it is not.
CREATE FUNCTION mesh_smooth(p_mesh text) RETURNS void AS $$
  WITH corner AS (
    SELECT t.tri_id, v.p, v.k,
           v3_cross(t.b - t.a, t.c - t.a) AS w   -- unnormalised: length = 2*area
    FROM tri t JOIN mesh m USING (mesh_id)
         CROSS JOIN LATERAL (VALUES (t.a, 1), (t.b, 2), (t.c, 3)) AS v(p, k)
    WHERE m.name = p_mesh
  ), vn AS (
    SELECT p, v3_unit(sum(w)) AS n FROM corner GROUP BY p
  ), per_tri AS (
    -- Pivot the three corners back onto one row.  vec3 has no max(), and
    -- inventing an ordering for it just to pivot would be worse than this.
    SELECT c.tri_id,
           (array_agg(vn.n) FILTER (WHERE c.k = 1))[1] AS na,
           (array_agg(vn.n) FILTER (WHERE c.k = 2))[1] AS nb,
           (array_agg(vn.n) FILTER (WHERE c.k = 3))[1] AS nc
    FROM corner c JOIN vn USING (p) GROUP BY c.tri_id
  )
  UPDATE tri SET na = p.na, nb = p.nb, nc = p.nc
  FROM per_tri p WHERE tri.tri_id = p.tri_id
$$ LANGUAGE sql;

-- ---------------------------------------------------------------------------
-- Wavefront OBJ.
--
-- Supports v / vn / f, faces as any polygon (fan-triangulated), corner
-- references in all of the 1, 1/2, 1//3 and 1/2/3 spellings, and negative
-- (relative) indices.  Everything else in the format is ignored, which is
-- enough to read what a modeller exports as a plain triangle mesh.
-- ---------------------------------------------------------------------------

CREATE FUNCTION mesh_load_obj(p_name text, p_material text, p_obj text,
                              p_scale float8 DEFAULT 1.0,
                              p_yaw   float8 DEFAULT 0.0,
                              p_at    vec3   DEFAULT ROW(0,0,0)::vec3,
                              p_smooth boolean DEFAULT false,
                              p_pitch float8 DEFAULT 0.0) RETURNS int AS $$
DECLARE
  m_id int := mesh_new(p_name, p_material);
  n_tri int;
  n_norm int;
BEGIN
  WITH ln AS (
    SELECT i, btrim(l) AS l
    FROM regexp_split_to_table(p_obj, E'\r?\n') WITH ORDINALITY AS s(l, i)
  ), tok AS (
    SELECT i, regexp_split_to_array(l, E'\\s+') AS w FROM ln WHERE l <> ''
  ), vert AS (
    SELECT row_number() OVER (ORDER BY i) AS vi,
           v3_place(ROW(w[2]::float8, w[3]::float8, w[4]::float8)::vec3,
                    p_scale, p_yaw, p_at, p_pitch) AS p
    FROM tok WHERE w[1] = 'v'
  ), norm AS (
    SELECT row_number() OVER (ORDER BY i) AS ni,
           -- Normals rotate but must not scale or translate.
           v3_rot(ROW(w[2]::float8, w[3]::float8, w[4]::float8)::vec3,
                  p_yaw, p_pitch) AS n
    FROM tok WHERE w[1] = 'vn'
  ), sizes AS (
    SELECT (SELECT count(*) FROM vert) AS nv, (SELECT count(*) FROM norm) AS nn
  ), face AS (
    -- Fan-triangulate: corner 1 pairs with each adjacent pair after it.
    SELECT w[2] AS c0, w[k] AS c1, w[k + 1] AS c2
    FROM tok, LATERAL generate_series(3, array_length(w, 1) - 1) g(k)
    WHERE w[1] = 'f' AND array_length(w, 1) >= 4
  ), ref AS (
    SELECT
      -- A negative OBJ index counts back from the end of the list so far.
      (SELECT CASE WHEN x < 0 THEN s.nv + x + 1 ELSE x END
       FROM (SELECT split_part(f.c0, '/', 1)::int) AS q(x)) AS v0,
      (SELECT CASE WHEN x < 0 THEN s.nv + x + 1 ELSE x END
       FROM (SELECT split_part(f.c1, '/', 1)::int) AS q(x)) AS v1,
      (SELECT CASE WHEN x < 0 THEN s.nv + x + 1 ELSE x END
       FROM (SELECT split_part(f.c2, '/', 1)::int) AS q(x)) AS v2,
      (SELECT CASE WHEN x < 0 THEN s.nn + x + 1 ELSE x END
       FROM (SELECT nullif(split_part(f.c0, '/', 3), '')::int) AS q(x)) AS n0,
      (SELECT CASE WHEN x < 0 THEN s.nn + x + 1 ELSE x END
       FROM (SELECT nullif(split_part(f.c1, '/', 3), '')::int) AS q(x)) AS n1,
      (SELECT CASE WHEN x < 0 THEN s.nn + x + 1 ELSE x END
       FROM (SELECT nullif(split_part(f.c2, '/', 3), '')::int) AS q(x)) AS n2
    FROM face f, sizes s
  )
  INSERT INTO tri (mesh_id, a, b, c, na, nb, nc)
  SELECT m_id, a.p, b.p, c.p, na.n, nb.n, nc.n
  FROM ref r
       JOIN vert a ON a.vi = r.v0
       JOIN vert b ON b.vi = r.v1
       JOIN vert c ON c.vi = r.v2
       LEFT JOIN norm na ON na.ni = r.n0
       LEFT JOIN norm nb ON nb.ni = r.n1
       LEFT JOIN norm nc ON nc.ni = r.n2;

  SELECT count(*), count(na) INTO n_tri, n_norm FROM tri WHERE mesh_id = m_id;
  IF n_tri = 0 THEN
    RAISE EXCEPTION 'mesh % : no faces found in the OBJ text', p_name;
  END IF;
  IF p_smooth AND n_norm = 0 THEN
    PERFORM mesh_smooth(p_name);
  END IF;
  RETURN m_id;
END $$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Primitive generators.  These exist so a scene can be written without an
-- external asset, and because a sphere is the honest test of smooth normals:
-- its vertex normals are known analytically, so any faceting that shows up is
-- the tracer's fault rather than the mesh's.
-- ---------------------------------------------------------------------------

CREATE FUNCTION mesh_add_quad(p_name text, p_material text, half float8,
                              p_at vec3 DEFAULT ROW(0,0,0)::vec3) RETURNS int AS $$
DECLARE m int := mesh_new(p_name, p_material);
BEGIN
  INSERT INTO tri (mesh_id, a, b, c) VALUES
    (m, ROW(-half,0,-half)::vec3 + p_at, ROW(-half,0, half)::vec3 + p_at,
        ROW( half,0, half)::vec3 + p_at),
    (m, ROW(-half,0,-half)::vec3 + p_at, ROW( half,0, half)::vec3 + p_at,
        ROW( half,0,-half)::vec3 + p_at);
  RETURN m;
END $$ LANGUAGE plpgsql;

CREATE FUNCTION mesh_add_box(p_name text, p_material text, half float8,
                             p_at vec3 DEFAULT ROW(0,0,0)::vec3,
                             p_yaw float8 DEFAULT 0.0) RETURNS int AS $$
DECLARE m int := mesh_new(p_name, p_material);
BEGIN
  -- Six faces, two triangles each, wound counter-clockwise from outside.  No
  -- vertex normals: a box should stay faceted.
  INSERT INTO tri (mesh_id, a, b, c)
  SELECT m, v3_place(q.a, half, p_yaw, p_at),
            v3_place(q.b, half, p_yaw, p_at),
            v3_place(q.c, half, p_yaw, p_at)
  FROM (VALUES
    (ROW(-1,-1, 1)::vec3, ROW( 1,-1, 1)::vec3, ROW( 1, 1, 1)::vec3),
    (ROW(-1,-1, 1)::vec3, ROW( 1, 1, 1)::vec3, ROW(-1, 1, 1)::vec3),
    (ROW( 1,-1,-1)::vec3, ROW(-1,-1,-1)::vec3, ROW(-1, 1,-1)::vec3),
    (ROW( 1,-1,-1)::vec3, ROW(-1, 1,-1)::vec3, ROW( 1, 1,-1)::vec3),
    (ROW( 1,-1, 1)::vec3, ROW( 1,-1,-1)::vec3, ROW( 1, 1,-1)::vec3),
    (ROW( 1,-1, 1)::vec3, ROW( 1, 1,-1)::vec3, ROW( 1, 1, 1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW(-1,-1, 1)::vec3, ROW(-1, 1, 1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW(-1, 1, 1)::vec3, ROW(-1, 1,-1)::vec3),
    (ROW(-1, 1, 1)::vec3, ROW( 1, 1, 1)::vec3, ROW( 1, 1,-1)::vec3),
    (ROW(-1, 1, 1)::vec3, ROW( 1, 1,-1)::vec3, ROW(-1, 1,-1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW( 1,-1,-1)::vec3, ROW( 1,-1, 1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW( 1,-1, 1)::vec3, ROW(-1,-1, 1)::vec3)
  ) AS q(a, b, c);
  RETURN m;
END $$ LANGUAGE plpgsql;

CREATE FUNCTION mesh_add_sphere(p_name text, p_material text, radius float8,
                                p_at vec3 DEFAULT ROW(0,0,0)::vec3,
                                seg int DEFAULT 24) RETURNS int AS $$
DECLARE m int := mesh_new(p_name, p_material);
BEGIN
  INSERT INTO tri (mesh_id, a, b, c, na, nb, nc)
  SELECT m, p_at + n00 * radius, p_at + q.n1 * radius, p_at + q.n2 * radius,
            n00, q.n1, q.n2
  FROM (
    SELECT
      ROW(sin(pi()*i/seg)*cos(2*pi()*j/seg), cos(pi()*i/seg),
          sin(pi()*i/seg)*sin(2*pi()*j/seg))::vec3 AS n00,
      ROW(sin(pi()*(i+1)/seg)*cos(2*pi()*j/seg), cos(pi()*(i+1)/seg),
          sin(pi()*(i+1)/seg)*sin(2*pi()*j/seg))::vec3 AS n10,
      ROW(sin(pi()*i/seg)*cos(2*pi()*(j+1)/seg), cos(pi()*i/seg),
          sin(pi()*i/seg)*sin(2*pi()*(j+1)/seg))::vec3 AS n01,
      ROW(sin(pi()*(i+1)/seg)*cos(2*pi()*(j+1)/seg), cos(pi()*(i+1)/seg),
          sin(pi()*(i+1)/seg)*sin(2*pi()*(j+1)/seg))::vec3 AS n11
    FROM generate_series(0, seg-1) a(i), generate_series(0, seg-1) b(j)
  -- Wound so the facet normal agrees with the analytic vertex normal.  Get
  -- this backwards and the sphere renders as a black silhouette: every hit
  -- reads as a back face, the shading normal is flipped inward, and the
  -- mirror ray is fired into the object.
  ) s CROSS JOIN LATERAL (VALUES (s.n11, s.n10), (s.n01, s.n11)) AS q(n1, n2)
  -- Degenerate slivers at the two poles, where n00 = n01 or n10 = n11.
  WHERE v3_len(v3_cross(q.n1 - n00, q.n2 - n00)) > 1e-12;
  RETURN m;
END $$ LANGUAGE plpgsql;
