-- ---------------------------------------------------------------------------
-- Meshes, materials, and the acceleration structure.
--
-- Geometry lives in tables.  A scene is a set of meshes, each a bag of
-- triangles pointing at a material; changing what a mesh is made of is an
-- INSERT, and changing how it looks is an UPDATE of one foreign key.
--
-- The shapes of the queries here were chosen by measurement, not taste, and
-- two results drove every decision:
--
--   * Intersection must be ONE set-based join over every live ray, not a
--     scalar function called per ray.  A correlated per-ray subquery over the
--     same geometry measured 1097 ms where the flat join measured 388 ms --
--     the per-ray rescan setup costs more than the arithmetic it performs.
--
--   * A ray must carry its inverse direction as a real column.  Computing it
--     in a LATERAL is not enough: the planner pulls a single-row Result up
--     into the join filter and then re-evaluates the whole expression at each
--     of the twelve places the slab test mentions it.
--
-- Both are the same lesson the tracer already learned once -- a SQL function
-- body is macro-expanded into its caller -- arriving in a new disguise.
-- ---------------------------------------------------------------------------

-- Material kinds.  These drive every branch in the transport code, which no
-- longer knows the names of any particular object in the scene.
CREATE FUNCTION mat_diffuse() RETURNS int AS $$ SELECT 0 $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;
CREATE FUNCTION mat_metal()   RETURNS int AS $$ SELECT 1 $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;
CREATE FUNCTION mat_glass()   RETURNS int AS $$ SELECT 2 $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE TABLE material (
  mat_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text   NOT NULL UNIQUE,
  kind    int    NOT NULL CHECK (kind BETWEEN 0 AND 2),
  albedo  vec3   NOT NULL DEFAULT ROW(0.8, 0.8, 0.8)::vec3,
  -- Second checker colour and cell size.  checker = 0 means a plain surface;
  -- the pattern is procedural rather than a texture because a texture would
  -- need UVs, and nothing else here does.
  albedo2 vec3   NOT NULL DEFAULT ROW(0.8, 0.8, 0.8)::vec3,
  checker float8 NOT NULL DEFAULT 0.0,
  tint    vec3   NOT NULL DEFAULT ROW(1, 1, 1)::vec3,   -- metal F0
  -- Index of refraction per channel.  Three different values is what splits
  -- white light: the dispersion is a property of the material, not of the
  -- tracer, so a second glass with a different spread is just another row.
  ior     vec3   NOT NULL DEFAULT ROW(1.5, 1.5, 1.5)::vec3,
  absorb  vec3   NOT NULL DEFAULT ROW(0, 0, 0)::vec3,   -- Beer-Lambert
  spec_e  float8 NOT NULL DEFAULT 260.0,                -- specular exponent
  spec_k  float8 NOT NULL DEFAULT 2.0,                  -- specular strength
  f0      float8 NOT NULL DEFAULT 0.045,                -- reflectance head-on
  kr_max  float8 NOT NULL DEFAULT 1.0                   -- reflectance ceiling
);

CREATE TABLE mesh (
  mesh_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text NOT NULL UNIQUE,
  mat_id  int  NOT NULL REFERENCES material(mat_id)
);

-- Vertex normals are nullable: a mesh with none is shaded flat off its
-- geometric normal, which is what a box wants and a sphere does not.
CREATE TABLE tri (
  tri_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesh_id int  NOT NULL REFERENCES mesh(mesh_id) ON DELETE CASCADE,
  a vec3 NOT NULL, b vec3 NOT NULL, c vec3 NOT NULL,
  na vec3, nb vec3, nc vec3,
  cl int                       -- BVH leaf, assigned by scene_reindex()
);
CREATE INDEX tri_cl_idx   ON tri (cl);
CREATE INDEX tri_mesh_idx ON tri (mesh_id);

-- Two levels of bounding volume: one box per mesh, one per leaf cluster.
CREATE TABLE bvh_node (
  cl      int PRIMARY KEY,
  mesh_id int  NOT NULL REFERENCES mesh(mesh_id) ON DELETE CASCADE,
  lo vec3 NOT NULL, hi vec3 NOT NULL
);
CREATE TABLE mesh_box (
  mesh_id int PRIMARY KEY REFERENCES mesh(mesh_id) ON DELETE CASCADE,
  lo vec3 NOT NULL, hi vec3 NOT NULL
);

-- ---------------------------------------------------------------------------
-- Ray/geometry tests.
-- ---------------------------------------------------------------------------

-- Guard against an exactly axis-parallel direction component.  Substituting a
-- tiny value rather than NULL keeps the slab arithmetic branch-free: the
-- resulting huge interval either swallows the axis or inverts into a miss,
-- which is the right answer in both cases.
CREATE FUNCTION nz(v float8) RETURNS float8
  AS $$ SELECT CASE WHEN abs(v) < 1e-12 THEN 1e-12 ELSE v END $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION v3_inv(d vec3) RETURNS vec3
  AS $$ SELECT ROW(1.0 / nz((d).x), 1.0 / nz((d).y), 1.0 / nz((d).z))::vec3 $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Slab test against an AABB, given the ray's precomputed inverse direction.
--
-- Deliberately FROM-less so it inlines, even though that makes the planner
-- evaluate each of the six slab products twice -- once under least(), once
-- under greatest().  The duplicated arithmetic is cheaper than the call it
-- avoids: the same test written in PL/pgSQL with locals measured 782 ms
-- against this version's 415 ms over a million boxes.
CREATE FUNCTION box_hit(o vec3, iv vec3, lo vec3, hi vec3) RETURNS boolean AS $$
  SELECT least(greatest(((lo).x - (o).x) * (iv).x, ((hi).x - (o).x) * (iv).x),
               greatest(((lo).y - (o).y) * (iv).y, ((hi).y - (o).y) * (iv).y),
               greatest(((lo).z - (o).z) * (iv).z, ((hi).z - (o).z) * (iv).z))
       >= greatest(least(((lo).x - (o).x) * (iv).x, ((hi).x - (o).x) * (iv).x),
                   least(((lo).y - (o).y) * (iv).y, ((hi).y - (o).y) * (iv).y),
                   least(((lo).z - (o).z) * (iv).z, ((hi).z - (o).z) * (iv).z),
                   1e-4)
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Moller-Trumbore, returning only the distance.
--
-- PL/pgSQL because every intermediate is used more than once, and because the
-- early rejections matter: most candidate triangles fail the u or v test, and
-- a local variable lets them fail after a third of the arithmetic.  The
-- barycentric coordinates are deliberately NOT returned -- they are needed
-- only for the one triangle a ray actually lands on, so recovering them once
-- per ray afterwards is far cheaper than returning them from every test.
CREATE FUNCTION tri_hit(o vec3, d vec3, a vec3, b vec3, c vec3) RETURNS float8 AS $$
DECLARE
  e1x float8 := (b).x-(a).x; e1y float8 := (b).y-(a).y; e1z float8 := (b).z-(a).z;
  e2x float8 := (c).x-(a).x; e2y float8 := (c).y-(a).y; e2z float8 := (c).z-(a).z;
  pvx float8; pvy float8; pvz float8; det float8; inv float8;
  tvx float8; tvy float8; tvz float8; qvx float8; qvy float8; qvz float8;
  u float8; v float8; t float8;
BEGIN
  pvx := (d).y*e2z - (d).z*e2y;
  pvy := (d).z*e2x - (d).x*e2z;
  pvz := (d).x*e2y - (d).y*e2x;
  det := e1x*pvx + e1y*pvy + e1z*pvz;
  IF abs(det) < 1e-12 THEN RETURN NULL; END IF;   -- ray parallel to the plane
  inv := 1.0 / det;
  tvx := (o).x-(a).x; tvy := (o).y-(a).y; tvz := (o).z-(a).z;
  u := (tvx*pvx + tvy*pvy + tvz*pvz) * inv;
  IF u < 0.0 OR u > 1.0 THEN RETURN NULL; END IF;
  qvx := tvy*e1z - tvz*e1y;
  qvy := tvz*e1x - tvx*e1z;
  qvz := tvx*e1y - tvy*e1x;
  v := ((d).x*qvx + (d).y*qvy + (d).z*qvz) * inv;
  IF v < 0.0 OR u + v > 1.0 THEN RETURN NULL; END IF;
  t := (e2x*qvx + e2y*qvy + e2z*qvz) * inv;
  IF t > 1e-4 THEN RETURN t; END IF;
  RETURN NULL;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- Barycentric coordinates (u, v, w) of the point where the ray meets the
-- triangle's plane.  Called once per ray, for the winning triangle only.
CREATE FUNCTION tri_bary(o vec3, d vec3, a vec3, b vec3, c vec3) RETURNS vec3 AS $$
DECLARE
  e1 vec3 := b - a; e2 vec3 := c - a; tv vec3 := o - a;
  pv vec3; qv vec3; inv float8; u float8; v float8;
BEGIN
  pv := v3_cross(d, e2);
  inv := 1.0 / nz(v3_dot(e1, pv));
  qv := v3_cross(tv, e1);
  u := v3_dot(tv, pv) * inv;
  v := v3_dot(d, qv) * inv;
  RETURN ROW(u, v, 1.0 - u - v)::vec3;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- Geometric (facet) normal, unit length.
CREATE FUNCTION tri_normal(a vec3, b vec3, c vec3) RETURNS vec3
  AS $$ SELECT v3_unit(v3_cross(b - a, c - a)) $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Shading normal at barycentric (u, v): the interpolated vertex normals when
-- the mesh carries them, the facet normal when it does not.
CREATE FUNCTION tri_shading_normal(t tri, bc vec3) RETURNS vec3 AS $$
  SELECT CASE
    WHEN t.na IS NULL THEN tri_normal(t.a, t.b, t.c)
    ELSE v3_unit(t.na * (bc).z + t.nb * (bc).x + t.nc * (bc).y)
  END $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- Nearest hit, as an aggregate.
--
-- Reducing millions of candidates to one row per ray with DISTINCT ON means
-- sorting every candidate; this picks the minimum in a single hash pass
-- instead.  It is the same trick as the vec3 sum aggregate: give the executor
-- a combine function and the reduction parallelises for free.
-- ---------------------------------------------------------------------------

CREATE TYPE cand AS (t float8, tri_id int);

-- What a ray found.  The normal is already flipped to face the incoming ray,
-- with `back` recording whether the geometric normal pointed away -- the
-- refraction code needs to know which side of a surface it is standing on.
-- `mat` is 0 for a miss, which is the only object identity left in the
-- tracer: everything else it needs to know arrives from the material row.
CREATE TYPE hit AS (
  t    float8,
  mat  int,
  p    vec3,
  n    vec3,
  back boolean
);

CREATE FUNCTION cand_min(a cand, b cand) RETURNS cand AS $$
  SELECT CASE WHEN (b).t IS NULL THEN a
              WHEN (a).t IS NULL OR (b).t < (a).t THEN b
              ELSE a END
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE AGGREGATE nearest(cand) (
  SFUNC = cand_min, STYPE = cand, COMBINEFUNC = cand_min, PARALLEL = SAFE);

-- Assemble a hit record from the winning candidate.  Called once per ray
-- rather than once per candidate, which is what makes it affordable to
-- recover the barycentric coordinates here instead of returning them from
-- every triangle test.
--
-- `back` is decided by the GEOMETRIC normal even though the shading normal is
-- what gets returned: an interpolated normal near a silhouette can point the
-- wrong way relative to the facet, and refraction needs to know which side of
-- the surface it is really standing on.
CREATE FUNCTION make_hit(o vec3, d vec3, c cand, t tri, mat int) RETURNS hit AS $$
DECLARE
  gn vec3;
  sn vec3;
  bk boolean;
BEGIN
  IF (c).tri_id IS NULL THEN
    RETURN ROW(0.0, 0, o, -d, false)::hit;      -- miss: the ray sees the sky
  END IF;
  gn := tri_normal(t.a, t.b, t.c);
  sn := tri_shading_normal(t, tri_bary(o, d, t.a, t.b, t.c));
  bk := v3_dot(d, gn) > 0.0;
  RETURN ROW((c).t, mat, o + d * (c).t,
             CASE WHEN bk THEN -sn ELSE sn END, bk)::hit;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- Building the BVH.
--
-- Two levels only, because the number of join levels has to be written into
-- the query text -- a tree of arbitrary depth would need a recursive descent
-- per bounce, and the bounce loop is already the outer recursion.  Leaves are
-- runs of Morton-ordered triangles, which keeps a leaf spatially compact:
-- grouping by insertion order instead produced boxes that spanned the whole
-- object and filtered nothing (measured slower than no BVH at all).
-- ---------------------------------------------------------------------------

-- Spread the low 10 bits of n so that two zero bits sit between each pair.
CREATE FUNCTION part1by2(n bigint) RETURNS bigint AS $$
DECLARE x bigint := n & 1023;
BEGIN
  x := (x | (x << 16)) &  50331903;
  x := (x | (x <<  8)) &  50393103;
  x := (x | (x <<  4)) &  51130563;
  x := (x | (x <<  2)) & 153391689;
  RETURN x;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION scene_reindex(p_leaf int DEFAULT NULL) RETURNS void AS $$
BEGIN
  -- Leaf size trades box tests against triangle tests.  The balance is not
  -- sqrt(n): a triangle test costs about three times a box test, so the
  -- optimum sits well below it.  The default was measured, not derived.
  WITH cen AS (
    SELECT tri_id, mesh_id,
           ((a).x + (b).x + (c).x) / 3.0 AS cx,
           ((a).y + (b).y + (c).y) / 3.0 AS cy,
           ((a).z + (b).z + (c).z) / 3.0 AS cz
    FROM tri
  ), bnd AS (
    SELECT mesh_id, min(cx) mnx, max(cx) mxx, min(cy) mny,
           max(cy) mxy, min(cz) mnz, max(cz) mxz,
           -- sqrt(n)/3, measured: for the default scene's 1104-triangle ball
           -- that is 11, and a sweep over 4..40 put the minimum at 8-12
           -- (798 ms against 1380 ms for plain sqrt(n)).  Below it the leaf
           -- boxes themselves start costing more than the triangles they skip.
           coalesce(p_leaf, greatest(4, least(48,
                    ceil(sqrt(count(*)::float8) / 3.0)::int))) AS leaf
    FROM cen GROUP BY mesh_id
  ), code AS (
    SELECT c.tri_id, c.mesh_id, b.leaf,
           part1by2((1023.0 * (c.cx - b.mnx) / nz(b.mxx - b.mnx))::bigint)
        | (part1by2((1023.0 * (c.cy - b.mny) / nz(b.mxy - b.mny))::bigint) << 1)
        | (part1by2((1023.0 * (c.cz - b.mnz) / nz(b.mxz - b.mnz))::bigint) << 2) AS mo
    FROM cen c JOIN bnd b USING (mesh_id)
  ), grp AS (
    SELECT tri_id, mesh_id,
           ((row_number() OVER (PARTITION BY mesh_id ORDER BY mo, tri_id) - 1)
            / leaf)::int AS g
    FROM code
  )
  UPDATE tri SET cl = d.cl FROM (
    SELECT tri_id, dense_rank() OVER (ORDER BY mesh_id, g)::int AS cl FROM grp
  ) d WHERE tri.tri_id = d.tri_id;

  DELETE FROM bvh_node;
  INSERT INTO bvh_node (cl, mesh_id, lo, hi)
  SELECT cl, min(mesh_id),
         ROW(min((v).x), min((v).y), min((v).z))::vec3,
         ROW(max((v).x), max((v).y), max((v).z))::vec3
  FROM (SELECT cl, mesh_id, unnest(ARRAY[a, b, c]) AS v FROM tri) u
  GROUP BY cl;

  DELETE FROM mesh_box;
  INSERT INTO mesh_box (mesh_id, lo, hi)
  SELECT mesh_id,
         ROW(min((lo).x), min((lo).y), min((lo).z))::vec3,
         ROW(max((hi).x), max((hi).y), max((hi).z))::vec3
  FROM bvh_node GROUP BY mesh_id;

  ANALYZE tri;
  ANALYZE bvh_node;
  ANALYZE mesh_box;
END $$ LANGUAGE plpgsql;

-- Nearest hit for a single ray.
--
-- The renderer does NOT use this -- it intersects every live ray in one join,
-- because a call per ray is what made the first version slow.  This exists so
-- the geometry can be tested and poked at from psql, and so a bug in the BVH
-- can be caught by comparing it against a brute-force scan.
CREATE FUNCTION scene_hit(o vec3, d vec3) RETURNS hit AS $$
DECLARE
  iv   vec3 := v3_inv(d);
  bt   float8;
  bid  int;
  tr   tri;
  mid  int;
BEGIN
  -- Selected field by field rather than straight into a `cand` variable:
  -- SELECT ... INTO a composite target assigns the query's COLUMNS to the
  -- target's FIELDS, so a single composite-valued column would land in t.
  SELECT (q.c).t, (q.c).tri_id INTO bt, bid
  FROM (
    SELECT nearest(ROW(x.t, t.tri_id)::cand) AS c
    FROM mesh_box mb
         JOIN bvh_node n ON n.mesh_id = mb.mesh_id
         JOIN tri t      ON t.cl = n.cl
         CROSS JOIN LATERAL (SELECT tri_hit(o, d, t.a, t.b, t.c) OFFSET 0) AS x(t)
    WHERE box_hit(o, iv, mb.lo, mb.hi)
      AND box_hit(o, iv, n.lo, n.hi)
      AND x.t IS NOT NULL
  ) q;

  IF bid IS NULL THEN
    RETURN make_hit(o, d, NULL::cand, NULL::tri, 0);
  END IF;
  SELECT * INTO tr FROM tri WHERE tri_id = bid;
  SELECT ms.mat_id INTO mid FROM mesh ms WHERE ms.mesh_id = tr.mesh_id;
  RETURN make_hit(o, d, ROW(bt, bid)::cand, tr, mid);
END $$ LANGUAGE plpgsql STABLE PARALLEL SAFE;

-- The material a hit landed on, for callers holding only a hit record.
CREATE FUNCTION mat_of(h hit) RETURNS material AS $$
  SELECT * FROM material WHERE mat_id = (h).mat
$$ LANGUAGE sql STABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- Getting geometry in.
-- ---------------------------------------------------------------------------

-- Scale, then pitch about X, then yaw about Y, then translate.  Two angles
-- rather than a full matrix type: it is the least that can aim an arbitrary
-- mesh, and a 4x4 would need a type, an operator and an inverse-transpose for
-- the normals to earn its place.
CREATE FUNCTION v3_rot(p vec3, yaw float8, pitch float8) RETURNS vec3 AS $$
DECLARE
  y float8 := (p).y * cos(pitch) - (p).z * sin(pitch);
  z float8 := (p).y * sin(pitch) + (p).z * cos(pitch);
BEGIN
  RETURN ROW( (p).x * cos(yaw) + z * sin(yaw),
              y,
             -(p).x * sin(yaw) + z * cos(yaw))::vec3;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION v3_place(p vec3, s float8, yaw float8, at vec3,
                         pitch float8 DEFAULT 0.0) RETURNS vec3
  AS $$ SELECT v3_rot(p * s, yaw, pitch) + at $$
  LANGUAGE sql IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION mesh_new(p_name text, p_material text) RETURNS int AS $$
DECLARE m int; mt int;
BEGIN
  SELECT mat_id INTO mt FROM material WHERE name = p_material;
  IF mt IS NULL THEN RAISE EXCEPTION 'no material named %', p_material; END IF;
  INSERT INTO mesh (name, mat_id) VALUES (p_name, mt) RETURNING mesh_id INTO m;
  RETURN m;
END $$ LANGUAGE plpgsql;

-- Assign a different material to an existing mesh.  This is the whole of
-- "selectable materials": geometry and appearance are separate rows.
CREATE FUNCTION mesh_set_material(p_mesh text, p_material text) RETURNS void AS $$
  UPDATE mesh SET mat_id = (SELECT mat_id FROM material WHERE name = p_material)
  WHERE name = p_mesh
$$ LANGUAGE sql;

-- Area-weighted vertex normals, averaged over every face meeting a vertex.
-- Vertices are matched by position, so a mesh loaded without normals comes
-- out smooth wherever it is geometrically closed and creased where it is not.
CREATE FUNCTION mesh_smooth(p_mesh text) RETURNS void AS $$
  WITH corner AS (
    SELECT t.tri_id, v.p, v.k,
           v3_cross(t.b - t.a, t.c - t.a) AS w   -- unnormalised: length = 2*area
    FROM tri t JOIN mesh m USING (mesh_id)
         CROSS JOIN LATERAL (VALUES (t.a, 1), (t.b, 2), (t.c, 3)) AS v(p, k)
    WHERE m.name = p_mesh
  ), vn AS (
    SELECT p, v3_unit(sum(w)) AS n FROM corner GROUP BY p
  ), per_tri AS (
    -- Pivot the three corners back onto one row.  vec3 has no max(), and
    -- inventing an ordering for it just to pivot would be worse than this.
    SELECT c.tri_id,
           (array_agg(vn.n) FILTER (WHERE c.k = 1))[1] AS na,
           (array_agg(vn.n) FILTER (WHERE c.k = 2))[1] AS nb,
           (array_agg(vn.n) FILTER (WHERE c.k = 3))[1] AS nc
    FROM corner c JOIN vn USING (p) GROUP BY c.tri_id
  )
  UPDATE tri SET na = p.na, nb = p.nb, nc = p.nc
  FROM per_tri p WHERE tri.tri_id = p.tri_id
$$ LANGUAGE sql;

-- ---------------------------------------------------------------------------
-- Wavefront OBJ.
--
-- Supports v / vn / f, faces as any polygon (fan-triangulated), corner
-- references in all of the 1, 1/2, 1//3 and 1/2/3 spellings, and negative
-- (relative) indices.  Everything else in the format is ignored, which is
-- enough to read what a modeller exports as a plain triangle mesh.
-- ---------------------------------------------------------------------------

CREATE FUNCTION mesh_load_obj(p_name text, p_material text, p_obj text,
                              p_scale float8 DEFAULT 1.0,
                              p_yaw   float8 DEFAULT 0.0,
                              p_at    vec3   DEFAULT ROW(0,0,0)::vec3,
                              p_smooth boolean DEFAULT false,
                              p_pitch float8 DEFAULT 0.0) RETURNS int AS $$
DECLARE
  m_id int := mesh_new(p_name, p_material);
  n_tri int;
  n_norm int;
BEGIN
  WITH ln AS (
    SELECT i, btrim(l) AS l
    FROM regexp_split_to_table(p_obj, E'\r?\n') WITH ORDINALITY AS s(l, i)
  ), tok AS (
    SELECT i, regexp_split_to_array(l, E'\\s+') AS w FROM ln WHERE l <> ''
  ), vert AS (
    SELECT row_number() OVER (ORDER BY i) AS vi,
           v3_place(ROW(w[2]::float8, w[3]::float8, w[4]::float8)::vec3,
                    p_scale, p_yaw, p_at, p_pitch) AS p
    FROM tok WHERE w[1] = 'v'
  ), norm AS (
    SELECT row_number() OVER (ORDER BY i) AS ni,
           -- Normals rotate but must not scale or translate.
           v3_rot(ROW(w[2]::float8, w[3]::float8, w[4]::float8)::vec3,
                  p_yaw, p_pitch) AS n
    FROM tok WHERE w[1] = 'vn'
  ), sizes AS (
    SELECT (SELECT count(*) FROM vert) AS nv, (SELECT count(*) FROM norm) AS nn
  ), face AS (
    -- Fan-triangulate: corner 1 pairs with each adjacent pair after it.
    SELECT w[2] AS c0, w[k] AS c1, w[k + 1] AS c2
    FROM tok, LATERAL generate_series(3, array_length(w, 1) - 1) g(k)
    WHERE w[1] = 'f' AND array_length(w, 1) >= 4
  ), ref AS (
    SELECT
      -- A negative OBJ index counts back from the end of the list so far.
      (SELECT CASE WHEN x < 0 THEN s.nv + x + 1 ELSE x END
       FROM (SELECT split_part(f.c0, '/', 1)::int) AS q(x)) AS v0,
      (SELECT CASE WHEN x < 0 THEN s.nv + x + 1 ELSE x END
       FROM (SELECT split_part(f.c1, '/', 1)::int) AS q(x)) AS v1,
      (SELECT CASE WHEN x < 0 THEN s.nv + x + 1 ELSE x END
       FROM (SELECT split_part(f.c2, '/', 1)::int) AS q(x)) AS v2,
      (SELECT CASE WHEN x < 0 THEN s.nn + x + 1 ELSE x END
       FROM (SELECT nullif(split_part(f.c0, '/', 3), '')::int) AS q(x)) AS n0,
      (SELECT CASE WHEN x < 0 THEN s.nn + x + 1 ELSE x END
       FROM (SELECT nullif(split_part(f.c1, '/', 3), '')::int) AS q(x)) AS n1,
      (SELECT CASE WHEN x < 0 THEN s.nn + x + 1 ELSE x END
       FROM (SELECT nullif(split_part(f.c2, '/', 3), '')::int) AS q(x)) AS n2
    FROM face f, sizes s
  )
  INSERT INTO tri (mesh_id, a, b, c, na, nb, nc)
  SELECT m_id, a.p, b.p, c.p, na.n, nb.n, nc.n
  FROM ref r
       JOIN vert a ON a.vi = r.v0
       JOIN vert b ON b.vi = r.v1
       JOIN vert c ON c.vi = r.v2
       LEFT JOIN norm na ON na.ni = r.n0
       LEFT JOIN norm nb ON nb.ni = r.n1
       LEFT JOIN norm nc ON nc.ni = r.n2;

  SELECT count(*), count(na) INTO n_tri, n_norm FROM tri WHERE mesh_id = m_id;
  IF n_tri = 0 THEN
    RAISE EXCEPTION 'mesh % : no faces found in the OBJ text', p_name;
  END IF;
  IF p_smooth AND n_norm = 0 THEN
    PERFORM mesh_smooth(p_name);
  END IF;
  RETURN m_id;
END $$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Primitive generators.  These exist so a scene can be written without an
-- external asset, and because a sphere is the honest test of smooth normals:
-- its vertex normals are known analytically, so any faceting that shows up is
-- the tracer's fault rather than the mesh's.
-- ---------------------------------------------------------------------------

CREATE FUNCTION mesh_add_quad(p_name text, p_material text, half float8,
                              p_at vec3 DEFAULT ROW(0,0,0)::vec3) RETURNS int AS $$
DECLARE m int := mesh_new(p_name, p_material);
BEGIN
  INSERT INTO tri (mesh_id, a, b, c) VALUES
    (m, ROW(-half,0,-half)::vec3 + p_at, ROW(-half,0, half)::vec3 + p_at,
        ROW( half,0, half)::vec3 + p_at),
    (m, ROW(-half,0,-half)::vec3 + p_at, ROW( half,0, half)::vec3 + p_at,
        ROW( half,0,-half)::vec3 + p_at);
  RETURN m;
END $$ LANGUAGE plpgsql;

CREATE FUNCTION mesh_add_box(p_name text, p_material text, half float8,
                             p_at vec3 DEFAULT ROW(0,0,0)::vec3,
                             p_yaw float8 DEFAULT 0.0) RETURNS int AS $$
DECLARE m int := mesh_new(p_name, p_material);
BEGIN
  -- Six faces, two triangles each, wound counter-clockwise from outside.  No
  -- vertex normals: a box should stay faceted.
  INSERT INTO tri (mesh_id, a, b, c)
  SELECT m, v3_place(q.a, half, p_yaw, p_at),
            v3_place(q.b, half, p_yaw, p_at),
            v3_place(q.c, half, p_yaw, p_at)
  FROM (VALUES
    (ROW(-1,-1, 1)::vec3, ROW( 1,-1, 1)::vec3, ROW( 1, 1, 1)::vec3),
    (ROW(-1,-1, 1)::vec3, ROW( 1, 1, 1)::vec3, ROW(-1, 1, 1)::vec3),
    (ROW( 1,-1,-1)::vec3, ROW(-1,-1,-1)::vec3, ROW(-1, 1,-1)::vec3),
    (ROW( 1,-1,-1)::vec3, ROW(-1, 1,-1)::vec3, ROW( 1, 1,-1)::vec3),
    (ROW( 1,-1, 1)::vec3, ROW( 1,-1,-1)::vec3, ROW( 1, 1,-1)::vec3),
    (ROW( 1,-1, 1)::vec3, ROW( 1, 1,-1)::vec3, ROW( 1, 1, 1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW(-1,-1, 1)::vec3, ROW(-1, 1, 1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW(-1, 1, 1)::vec3, ROW(-1, 1,-1)::vec3),
    (ROW(-1, 1, 1)::vec3, ROW( 1, 1, 1)::vec3, ROW( 1, 1,-1)::vec3),
    (ROW(-1, 1, 1)::vec3, ROW( 1, 1,-1)::vec3, ROW(-1, 1,-1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW( 1,-1,-1)::vec3, ROW( 1,-1, 1)::vec3),
    (ROW(-1,-1,-1)::vec3, ROW( 1,-1, 1)::vec3, ROW(-1,-1, 1)::vec3)
  ) AS q(a, b, c);
  RETURN m;
END $$ LANGUAGE plpgsql;

CREATE FUNCTION mesh_add_sphere(p_name text, p_material text, radius float8,
                                p_at vec3 DEFAULT ROW(0,0,0)::vec3,
                                seg int DEFAULT 24) RETURNS int AS $$
DECLARE m int := mesh_new(p_name, p_material);
BEGIN
  INSERT INTO tri (mesh_id, a, b, c, na, nb, nc)
  SELECT m, p_at + n00 * radius, p_at + q.n1 * radius, p_at + q.n2 * radius,
            n00, q.n1, q.n2
  FROM (
    SELECT
      ROW(sin(pi()*i/seg)*cos(2*pi()*j/seg), cos(pi()*i/seg),
          sin(pi()*i/seg)*sin(2*pi()*j/seg))::vec3 AS n00,
      ROW(sin(pi()*(i+1)/seg)*cos(2*pi()*j/seg), cos(pi()*(i+1)/seg),
          sin(pi()*(i+1)/seg)*sin(2*pi()*j/seg))::vec3 AS n10,
      ROW(sin(pi()*i/seg)*cos(2*pi()*(j+1)/seg), cos(pi()*i/seg),
          sin(pi()*i/seg)*sin(2*pi()*(j+1)/seg))::vec3 AS n01,
      ROW(sin(pi()*(i+1)/seg)*cos(2*pi()*(j+1)/seg), cos(pi()*(i+1)/seg),
          sin(pi()*(i+1)/seg)*sin(2*pi()*(j+1)/seg))::vec3 AS n11
    FROM generate_series(0, seg-1) a(i), generate_series(0, seg-1) b(j)
  -- Wound so the facet normal agrees with the analytic vertex normal.  Get
  -- this backwards and the sphere renders as a black silhouette: every hit
  -- reads as a back face, the shading normal is flipped inward, and the
  -- mirror ray is fired into the object.
  ) s CROSS JOIN LATERAL (VALUES (s.n11, s.n10), (s.n01, s.n11)) AS q(n1, n2)
  -- Degenerate slivers at the two poles, where n00 = n01 or n10 = n11.
  WHERE v3_len(v3_cross(q.n1 - n00, q.n2 - n00)) > 1e-12;
  RETURN m;
END $$ LANGUAGE plpgsql;
