-- ---------------------------------------------------------------------------
-- The scene: lighting, the sky, and the meshes that make up the default view.
--
-- Nothing below is known to the tracer.  The transport code reads material
-- rows and triangle rows; it has no idea that this particular scene contains
-- a sphere, and would trace a teapot with the same query.
-- ---------------------------------------------------------------------------

-- Lights are rows, for the reason materials are rows: nothing downstream
-- branches on *which* light it is looking at, so a rim light, a coloured fill,
-- or the several samples that make up one area light are INSERTs rather than
-- new SQL.  The renderer treats (hit, light) as its unit of work and resolves
-- every pair in one pass, so a second light costs a second shadow ray per lit
-- hit -- not a second traversal of the scene.
--
-- `pow` is radiant intensity: the shading divides it by the squared distance,
-- so the same number means the same brightness only at the same range.
--
-- sky_k and sky_e are the disc the sky paints where this light stands, which
-- is what makes a light visible in a mirror and in the background rather than
-- only on the surfaces it lights.  Keeping it here rather than as a constant
-- of the sky is what holds the two consistent: move the light and its
-- reflection moves with it.  It is a distant-sun approximation -- the
-- direction is measured from the world origin, not from the shading point --
-- and it defaults to zero, because a fill light that painted a second sun on
-- the horizon would be a surprise.
--
-- sky_dir is that direction, stored rather than derived per call, and it is
-- not a micro-optimisation.  Inlined, v3_unit is some forty expression nodes;
-- handed that, the pow_safe consuming it is far over the threshold at which
-- PostgreSQL gives up on inlining, and the disc term is evaluated once per
-- escaping ray.  Stored, the whole expression folds into the caller.
CREATE TABLE light (
  light_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text   NOT NULL UNIQUE,
  p       vec3   NOT NULL,
  col     vec3   NOT NULL DEFAULT ROW(1, 1, 1)::vec3,
  pow     float8 NOT NULL DEFAULT 100.0,
  sky_k   float8 NOT NULL DEFAULT 0.0,     -- sky disc brightness, 0 = invisible
  sky_e   float8 NOT NULL DEFAULT 420.0,   -- sky disc tightness
  sky_dir vec3 GENERATED ALWAYS AS (v3_unit(p)) STORED,
  -- v3_unit is undefined at the origin, and a NULL direction would poison the
  -- radiance sum silently rather than fail.
  CHECK ((p).x <> 0.0 OR (p).y <> 0.0 OR (p).z <> 0.0)
);

CREATE FUNCTION sky_bg(d vec3) RETURNS vec3 AS $$
  SELECT ROW(0.20, 0.40, 0.86)::vec3 * greatest((d).y, 0.0)
       + ROW(0.62, 0.76, 0.94)::vec3 * (1.0 - greatest((d).y, 0.0))
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- The disc one light paints on the sky, for a ray leaving along d.
--
-- The brightness goes through a local because `*` names its scalar operand
-- three times, once per component, and a pow_safe is well past the size at
-- which that stops inlining.  Bound first, the scale folds in and this costs
-- one PL/pgSQL invocation rather than an executor run per escaping ray.
CREATE FUNCTION sky_sun(d vec3, l light) RETURNS vec3 AS $$
DECLARE k float8 := l.sky_k
                  * pow_safe(greatest(v3_dot(d, l.sky_dir), 0.0), l.sky_e);
BEGIN
  RETURN l.col * k;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- The sky an escaping ray sees, background plus every visible light disc.
--
-- The renderer does NOT call this -- it sums the same discs set-based, one row
-- per (escaping ray, visible light), for the same reason it does not call
-- scene_hit: a query per ray costs more than the arithmetic in it.  This is
-- the scalar spelling, so the sky can be checked and plotted from psql.
CREATE FUNCTION sky(d vec3) RETURNS vec3 AS $$
  SELECT sky_bg(d) + (SELECT sum(sky_sun(d, l)) FROM light l WHERE l.sky_k > 0.0)
$$ LANGUAGE sql STABLE PARALLEL SAFE;

-- Surface colour at a point.  A checker material fades toward its average
-- with distance, so the pattern does not alias into noise near the horizon.
CREATE FUNCTION mat_albedo(m material, p vec3) RETURNS vec3 AS $$
DECLARE fade float8; mix float8;
BEGIN
  IF m.checker <= 0.0 THEN RETURN m.albedo; END IF;
  fade := least(1.0, greatest(0.0, (v3_len(p) - 14.0) / 22.0));
  mix  := CASE WHEN (floor((p).x / m.checker)
                   + floor((p).z / m.checker))::int % 2 = 0
               THEN 1.0 ELSE 0.0 END * (1.0 - fade)
        + 0.5 * fade;
  RETURN m.albedo * mix + m.albedo2 * (1.0 - mix);
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- The default scene.
-- ---------------------------------------------------------------------------

CREATE FUNCTION scene_clear() RETURNS void AS $$
  DELETE FROM tri;
  DELETE FROM mesh_box;
  DELETE FROM bvh_node;
  DELETE FROM mesh;
$$ LANGUAGE sql;

CREATE FUNCTION scene_default(sphere_seg int DEFAULT 24) RETURNS void AS $$
BEGIN
  PERFORM scene_clear();
  DELETE FROM material;
  DELETE FROM light;

  -- One key light, placed behind and to the side of the subjects rather than
  -- over the camera's shoulder: a frontal light throws every shadow behind the
  -- object that casts it, where the object itself hides it, and the render
  -- comes out looking flat.  It is the only light carrying a sky disc, so the
  -- highlight the chrome ball reflects is the light that is actually shading
  -- the floor.
  INSERT INTO light (name, p, col, pow, sky_k)
  VALUES ('key', ROW(5.2, 4.6, -2.4)::vec3, ROW(1.00, 0.96, 0.88)::vec3,
          125.0, 22.0);

  INSERT INTO material (name, kind, albedo, albedo2, checker, f0, kr_max)
  VALUES ('checker-tile', mat_diffuse(),
          ROW(0.90, 0.89, 0.86)::vec3, ROW(0.16, 0.17, 0.21)::vec3,
          1.0, 0.045,
          -- Physically this should approach 1 at grazing incidence, but an
          -- unclamped mirror floor reflects the bright uniform sky across the
          -- whole lower frame and erases its own shadows.
          0.17);

  INSERT INTO material (name, kind, tint, spec_e, spec_k)
  VALUES ('chrome', mat_metal(), ROW(0.96, 0.93, 0.86)::vec3, 260.0, 2.2);

  -- Crown glass, with the dispersion exaggerated so it reads at this
  -- resolution: blue is bent harder than red, which is what splits white
  -- light into a spectrum at every non-normal incidence.
  INSERT INTO material (name, kind, ior, absorb, spec_e, spec_k)
  VALUES ('crown-glass', mat_glass(),
          ROW(1.470, 1.530, 1.605)::vec3, ROW(0.28, 0.14, 0.16)::vec3,
          420.0, 1.6);

  PERFORM mesh_add_quad('ground', 'checker-tile', 40.0);
  PERFORM mesh_add_sphere('ball', 'chrome', 1.00,
                          ROW(-1.15, 1.00, -0.20)::vec3, sphere_seg);
  PERFORM mesh_add_box('block', 'crown-glass', 0.85,
                       ROW(1.35, 0.85, 0.55)::vec3, 0.42);

  PERFORM scene_reindex();
END $$ LANGUAGE plpgsql;

-- Build the default scene at install time so a fresh database can render.
DO $$ BEGIN PERFORM scene_default(); END $$;
