-- ---------------------------------------------------------------------------
-- The scene: lighting, the sky, and the meshes that make up the default view.
--
-- Nothing below is known to the tracer.  The transport code reads material
-- rows and triangle rows; it has no idea that this particular scene contains
-- a sphere, and would trace a teapot with the same query.
-- ---------------------------------------------------------------------------

-- Lights are rows, for the reason materials are rows: nothing downstream
-- branches on *which* light it is looking at, so a rim light or a coloured
-- fill is an INSERT rather than new SQL.  The renderer treats (hit, light) as
-- its unit of work and resolves every pair in one pass, so a second light
-- costs a second shadow ray per lit hit -- not a second traversal of the
-- scene.
--
-- An area light is one row too, and that is a decision worth defending,
-- because the obvious alternative works without any of this.  A softbox can be
-- approximated by N*N ordinary point lights spread over a rectangle at pow/N^2
-- each: no code at all, and it does produce a penumbra.  What it cannot
-- produce is an unbiased one.  Every hit in the frame sums the same N^2 rows,
-- so the error is identical everywhere and the penumbra comes out as N^2
-- terraces at fixed positions in the world -- and antialiasing cannot touch
-- them, because each sub-sample of a pixel is a separate hit that sees the
-- same light table.  Worse, the sample count ends up set by the tightest
-- specular lobe in the scene rather than by the softness wanted: at spec_e 260
-- a chrome ball resolves a 4x4 grid as four separate glints.
--
-- So the emitter stays one row with a shape, and the sampling moves to the
-- hit.  `u` and `v` are half-extents -- the light spans p +/- u +/- v -- and
-- `samples` is per axis, exactly as `aa` is: samples = 4 fires 16 shadow rays
-- per hit, as aa = 4 casts 16 camera rays per pixel.  Where those 16 land is
-- decorrelated per hit, which turns the terraces into noise, and noise is what
-- `aa` was already averaging.  That is the whole return: a pixel at aa = 2
-- covers four times as much of the emitter as its shadow-ray count suggests,
-- because its four sub-samples are four different hits.
--
-- `pow` is radiant intensity: the shading divides it by the squared distance,
-- so the same number means the same brightness only at the same range.
--
-- sky_k and sky_e are the disc the sky paints where this light stands, which
-- is what makes a light visible in a mirror and in the background rather than
-- only on the surfaces it lights.  Keeping it here rather than as a constant
-- of the sky is what holds the two consistent: move the light and its
-- reflection moves with it.  It is a distant-sun approximation -- the
-- direction is measured from the world origin, not from the shading point --
-- and it defaults to zero, because a fill light that painted a second sun on
-- the horizon would be a surprise.
--
-- sky_dir is that direction, stored rather than derived per call, and it is
-- not a micro-optimisation.  Inlined, v3_unit is some forty expression nodes;
-- handed that, the pow_safe consuming it is far over the threshold at which
-- PostgreSQL gives up on inlining, and the disc term is evaluated once per
-- escaping ray.  Stored, the whole expression folds into the caller.
CREATE TABLE light (
  light_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text   NOT NULL UNIQUE,
  p       vec3   NOT NULL,
  col     vec3   NOT NULL DEFAULT ROW(1, 1, 1)::vec3,
  pow     float8 NOT NULL DEFAULT 100.0,
  sky_k   float8 NOT NULL DEFAULT 0.0,     -- sky disc brightness, 0 = invisible
  sky_e   float8 NOT NULL DEFAULT 420.0,   -- sky disc tightness
  sky_dir vec3 GENERATED ALWAYS AS (v3_unit(p)) STORED,

  u       vec3   NOT NULL DEFAULT ROW(0, 0, 0)::vec3,  -- half-extent, one axis
  v       vec3   NOT NULL DEFAULT ROW(0, 0, 0)::vec3,  -- half-extent, the other
  samples int    NOT NULL DEFAULT 1,                   -- per axis, like aa

  -- Which way the panel faces, and therefore which half of the world it lights
  -- and how much of itself a surface can see.  NULL means a point light: no
  -- extent, no orientation, and no cosine.  Every reader has to test for that
  -- NULL explicitly rather than letting it flow into arithmetic, because
  -- greatest(NULL, 0.0) is 0.0 and would switch the light off in silence --
  -- the same trap that once painted 846 pixels pure black.
  nrm     vec3 GENERATED ALWAYS AS (
            CASE WHEN ((u).x = 0.0 AND (u).y = 0.0 AND (u).z = 0.0)
                   OR ((v).x = 0.0 AND (v).y = 0.0 AND (v).z = 0.0)
                 THEN NULL
                 ELSE v3_unit(v3_cross(u, v)) END) STORED,

  -- v3_unit is undefined at the origin, and a NULL direction would poison the
  -- radiance sum silently rather than fail.
  CHECK ((p).x <> 0.0 OR (p).y <> 0.0 OR (p).z <> 0.0),
  CHECK (samples >= 1)
);

-- A number that identifies a hit by *where it is* rather than by which row it
-- happens to be.
--
-- The obvious key for the jitter below is the hit id, and it is wrong in a way
-- that takes a while to surface.  `rt_hit.hid` is a bigserial, so it depends on
-- how many rays came before -- and adaptive sampling re-traces a subset of the
-- frame, which gives every re-traced hit a different id than the same sample
-- had in a uniform render.  Keyed on the id, a refined pixel samples the light
-- somewhere else and stops being bit-for-bit the pixel a uniform frame would
-- have produced.  Measured at 48x32: 588 of 1536 pixels.
--
-- A hit's position does not have that problem.  The same camera sample re-traced
-- produces the same intersection to the last bit, so this is stable under
-- re-tracing, while neighbouring pixels -- and the sub-samples within one pixel
-- -- land far enough apart to hash independently.  The multipliers are the usual
-- large primes and the quantisation is 1e-5 world units, which is two orders
-- finer than the closest two samples ever get.
CREATE FUNCTION hit_seed(hx float8, hy float8, hz float8) RETURNS bigint AS $$
  SELECT (round(hx * 1e5)::bigint * 73856093)
       # (round(hy * 1e5)::bigint * 19349663)
       # (round(hz * 1e5)::bigint * 83492791)
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Where on the emitter one hit should look, once per sample.
--
-- The grid is stratified rather than random: sample s takes cell
-- (s % samples, s / samples), so the emitter is always covered evenly and a
-- run of samples can never clump the way independent uniform draws do.  Only
-- the position *within* each cell is random, and it is a hash of the hit
-- rather than a random(), for three reasons that all matter here: it is
-- IMMUTABLE, so the planner may hoist and parallelise it; it is reproducible,
-- so a frame is a function of the scene and re-rendering it gives the same
-- bytes; and it decorrelates hit from hit, which is the entire point -- two
-- adjacent pixels, or two sub-samples of one pixel, look at different parts of
-- the light and their average covers more of it than either alone.
--
-- `seed` is hit_seed() of the point being shaded, and the light's own position
-- is mixed in so that two lights do not put their samples in the same places.
-- Its *position* and not its light_id: an identity column counts how many rows
-- have ever been inserted, so keying on it would make a frame depend on the
-- history of the session that built the scene rather than on the scene.  That
-- is not hypothetical -- it was caught by the suite's golden hashes disagreeing
-- with the same render from a fresh connection.
--
-- The renderer does NOT call this; it inlines the same arithmetic into the
-- shadow-ray CTAS, for the reason sky() is not called either -- a function
-- invocation per shadow ray costs more than the arithmetic in it.  This is the
-- scalar spelling, so a light's sample pattern can be plotted from psql, and
-- the test suite holds the two to the same answers.
CREATE FUNCTION light_sample(l light, seed bigint)
RETURNS TABLE (s int, p vec3) AS $$
  SELECT g.s, l.p + l.u * a.su + l.v * a.sv
  FROM generate_series(0, l.samples * l.samples - 1) AS g(s)
       CROSS JOIN LATERAL (
         SELECT hashint8(seed + hit_seed((l.p).x, (l.p).y, (l.p).z)
                         + g.s)) AS q(w)
       CROSS JOIN LATERAL (
         SELECT 2.0 * ((g.s % l.samples)::float8
                       + ((q.w & 65535)::float8 + 0.5) / 65536.0)
                     / l.samples::float8 - 1.0,
                2.0 * ((g.s / l.samples)::float8
                       + (((q.w >> 16) & 65535)::float8 + 0.5) / 65536.0)
                     / l.samples::float8 - 1.0) AS a(su, sv)
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- A rectangular light of a given size, aimed at a point.
--
-- The aim is what makes this worth a function rather than two INSERTs: the
-- half-extents have to span the plane the panel faces along, and their cross
-- product has to come out pointing at the subject rather than away from it,
-- which is a sign nobody wants to rediscover.  v = f x u rather than u x f is
-- the whole of it.
CREATE FUNCTION light_softbox(p_name text, p_p vec3, p_at vec3,
                              p_w float8, p_h float8,
                              p_samples int DEFAULT 2,
                              p_pow float8 DEFAULT 100.0,
                              p_col vec3 DEFAULT ROW(1, 1, 1)::vec3,
                              p_sky_k float8 DEFAULT 0.0,
                              p_sky_e float8 DEFAULT 420.0)
RETURNS int AS $$
DECLARE
  f  vec3 := v3_unit(p_at - p_p);
  up vec3;
  su vec3;
  id int;
BEGIN
  -- Any up vector will do except the one parallel to the aim, which would make
  -- the cross product zero and the panel's orientation undefined.
  up := CASE WHEN abs((f).y) > 0.999 THEN ROW(0, 0, 1)::vec3
                                     ELSE ROW(0, 1, 0)::vec3 END;
  su := v3_unit(v3_cross(f, up));
  INSERT INTO light (name, p, col, pow, sky_k, sky_e, u, v, samples)
  VALUES (p_name, p_p, p_col, p_pow, p_sky_k, p_sky_e,
          su * (p_w * 0.5), v3_cross(f, su) * (p_h * 0.5), p_samples)
  RETURNING light_id INTO id;
  RETURN id;
END $$ LANGUAGE plpgsql;

CREATE FUNCTION sky_bg(d vec3) RETURNS vec3 AS $$
  SELECT ROW(0.20, 0.40, 0.86)::vec3 * greatest((d).y, 0.0)
       + ROW(0.62, 0.76, 0.94)::vec3 * (1.0 - greatest((d).y, 0.0))
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- The disc one light paints on the sky, for a ray leaving along d.
--
-- The brightness goes through a local because `*` names its scalar operand
-- three times, once per component, and a pow_safe is well past the size at
-- which that stops inlining.  Bound first, the scale folds in and this costs
-- one PL/pgSQL invocation rather than an executor run per escaping ray.
CREATE FUNCTION sky_sun(d vec3, l light) RETURNS vec3 AS $$
DECLARE k float8 := l.sky_k
                  * pow_safe(greatest(v3_dot(d, l.sky_dir), 0.0), l.sky_e);
BEGIN
  RETURN l.col * k;
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- The sky an escaping ray sees, background plus every visible light disc.
--
-- The renderer does NOT call this -- it sums the same discs set-based, one row
-- per (escaping ray, visible light), for the same reason it does not call
-- scene_hit: a query per ray costs more than the arithmetic in it.  This is
-- the scalar spelling, so the sky can be checked and plotted from psql.
CREATE FUNCTION sky(d vec3) RETURNS vec3 AS $$
  SELECT sky_bg(d) + (SELECT sum(sky_sun(d, l)) FROM light l WHERE l.sky_k > 0.0)
$$ LANGUAGE sql STABLE PARALLEL SAFE;

-- Surface colour at a point.  A checker material fades toward its average
-- with distance, so the pattern does not alias into noise near the horizon.
CREATE FUNCTION mat_albedo(m material, p vec3) RETURNS vec3 AS $$
DECLARE fade float8; mix float8;
BEGIN
  IF m.checker <= 0.0 THEN RETURN m.albedo; END IF;
  fade := least(1.0, greatest(0.0, (v3_len(p) - 14.0) / 22.0));
  mix  := CASE WHEN (floor((p).x / m.checker)
                   + floor((p).z / m.checker))::int % 2 = 0
               THEN 1.0 ELSE 0.0 END * (1.0 - fade)
        + 0.5 * fade;
  RETURN m.albedo * mix + m.albedo2 * (1.0 - mix);
END $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;

-- ---------------------------------------------------------------------------
-- The default scene.
-- ---------------------------------------------------------------------------

CREATE FUNCTION scene_clear() RETURNS void AS $$
  DELETE FROM tri;
  DELETE FROM mesh_box;
  DELETE FROM bvh_node;
  DELETE FROM mesh;
$$ LANGUAGE sql;

CREATE FUNCTION scene_default(sphere_seg int DEFAULT 24) RETURNS void AS $$
BEGIN
  PERFORM scene_clear();
  DELETE FROM material;
  DELETE FROM light;

  -- One key light, placed behind and to the side of the subjects rather than
  -- over the camera's shoulder: a frontal light throws every shadow behind the
  -- object that casts it, where the object itself hides it, and the render
  -- comes out looking flat.  It is the only light carrying a sky disc, so the
  -- highlight the chrome ball reflects is the light that is actually shading
  -- the floor.
  --
  -- A two-unit panel rather than a point, aimed at what the default camera is
  -- aimed at.  Two samples per axis is four shadow rays per lit hit and costs
  -- about 60% of a frame at one sample per pixel; at the aa = 2 that render.sh
  -- defaults to, the four sub-samples of a pixel are four separate hits looking
  -- at four different parts of the panel, so a pixel averages sixteen points on
  -- the light and the grain measures lower than the point light's own checker
  -- aliasing.  Raise `samples` if a frame is wanted clean at aa = 1.
  --
  -- sky_e is derived from the size rather than chosen.  The disc is a cos^n
  -- lobe, which is at half brightness at sqrt(2 ln 2 / n) radians, and the
  -- panel is atan(1.0 / 7.35) = 0.135 radians across from the origin -- so
  -- n = 2 ln 2 / 0.135^2, about 80.  Left at the point light's 420 the ball
  -- would reflect a pinpoint from a source a hundred times that wide, which is
  -- the one place the sky disc's distant-sun approximation shows.
  PERFORM light_softbox('key',
                        ROW(5.2, 4.6, -2.4)::vec3,   -- where it is
                        ROW(0.05, 1.0, 0.0)::vec3,   -- what it aims at
                        2.0, 2.0, 2, 125.0,
                        ROW(1.00, 0.96, 0.88)::vec3, 22.0, 80.0);

  INSERT INTO material (name, kind, albedo, albedo2, checker, f0, kr_max)
  VALUES ('checker-tile', mat_diffuse(),
          ROW(0.90, 0.89, 0.86)::vec3, ROW(0.16, 0.17, 0.21)::vec3,
          1.0, 0.045,
          -- Physically this should approach 1 at grazing incidence, but an
          -- unclamped mirror floor reflects the bright uniform sky across the
          -- whole lower frame and erases its own shadows.
          0.17);

  INSERT INTO material (name, kind, tint, spec_e, spec_k)
  VALUES ('chrome', mat_metal(), ROW(0.96, 0.93, 0.86)::vec3, 260.0, 2.2);

  -- Crown glass, with the dispersion exaggerated so it reads at this
  -- resolution: blue is bent harder than red, which is what splits white
  -- light into a spectrum at every non-normal incidence.
  --
  -- How exaggerated is worth writing down, because the number that matters is
  -- not the index but the spread across the three channels.  At 0.060 this is
  -- an Abbe number of 8.8, against 64 for the BK7 the material is named after
  -- -- still seven times more dispersive than real glass, which is deliberate:
  -- a real spread of 0.008 separates red from blue by a seventh of a degree
  -- and does not survive being quantized to 8 bits.
  --
  -- It was 0.135, an Abbe number of 3.9, and that was too much -- the fringing
  -- read as the material's defining feature rather than as an edge effect.
  -- The green index is unchanged at 1.530, so the refraction itself is the
  -- same shape it always was; only the width of the colour split moved.
  INSERT INTO material (name, kind, ior, absorb, spec_e, spec_k)
  VALUES ('crown-glass', mat_glass(),
          ROW(1.500, 1.530, 1.560)::vec3, ROW(0.28, 0.14, 0.16)::vec3,
          420.0, 1.6);

  PERFORM mesh_add_quad('ground', 'checker-tile', 40.0);
  PERFORM mesh_add_sphere('ball', 'chrome', 1.00,
                          ROW(-1.15, 1.00, -0.20)::vec3, sphere_seg);
  PERFORM mesh_add_box('block', 'crown-glass', 0.85,
                       ROW(1.35, 0.85, 0.55)::vec3, 0.42);

  PERFORM scene_reindex();
END $$ LANGUAGE plpgsql;

-- Build the default scene at install time so a fresh database can render.
DO $$ BEGIN PERFORM scene_default(); END $$;
