-- ---------------------------------------------------------------------------
-- Renders that outlive the rendering.
--
-- `img` is a buffer: unlogged, dropped and rebuilt by every call to render().
-- So until this table existed nothing recorded what any picture was *of*, and
-- each render destroyed the one before it.  A frame row is the description and
-- the result together -- enough settings to reproduce the image, and the image.
-- ---------------------------------------------------------------------------

-- The PNG rather than the pixels, deliberately, and the reasoning is worth
-- keeping because "keep the pixels, you can always re-encode" is the obvious
-- instinct and it is wrong here.  `img` holds int in 0-255 that quantize() has
-- already put through exposure, the tone curve and a 1/2.2 gamma, then clipped.
-- The expensive thing -- radiance -- is gone by that point, so stored pixels
-- are not a cheaper route to a differently exposed image than re-tracing is.
-- They are only bigger: roughly 100 MB of rows against 419 kB of bytea for a
-- full HD frame, which is the difference between keeping a frame and keeping a
-- sequence of them.
--
-- A frame is a view of whatever geometry the database holds when it is
-- rendered; nothing here is scene-aware yet.  Reloading the engine drops this
-- table along with everything else.
CREATE TABLE frame (
  frame_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text UNIQUE,
  w           int    NOT NULL,
  h           int    NOT NULL,
  aa          int    NOT NULL DEFAULT 2,
  maxdepth    int    NOT NULL DEFAULT 5,
  exposure    float8 NOT NULL DEFAULT 1.35,
  cutoff      float8 NOT NULL DEFAULT 0.01,

  -- Nullable because null is the setting, not a missing one: no refinement
  -- pass at all, `aa` everywhere.  A number is how many 8-bit levels two
  -- neighbouring pixels may differ by before the finer grid is spent on them,
  -- so it shares a scale with the image rather than with the sampler.
  refine      int,

  -- The camera lives on the frame, not on the geometry.  A camera is a
  -- property of a view of a scene rather than of the scene, which is what
  -- makes a hundred viewpoints a hundred rows instead of a hundred databases.
  cam_from    vec3   NOT NULL DEFAULT cam_from(),
  cam_at      vec3   NOT NULL DEFAULT cam_at(),
  cam_fov     float8 NOT NULL DEFAULT cam_fov(),

  rendered_at timestamptz,
  elapsed_ms  int,
  png         bytea,

  CHECK (w > 0 AND h > 0 AND aa > 0 AND maxdepth >= 0),
  CHECK (refine IS NULL OR refine >= 0),
  CHECK (cam_fov > 0.0 AND cam_fov < 180.0),
  CHECK ((cam_from).x <> (cam_at).x OR (cam_from).y <> (cam_at).y
      OR (cam_from).z <> (cam_at).z)
);

-- Render what a frame row describes and store the result back into it.
--
-- This is the archival entry point; render() by argument stays the interactive
-- one.  Keeping them separate is what makes a sequence expressible: the rows
-- exist before any of them is traced, so a camera path is an INSERT ... SELECT
-- over generate_series and resuming an interrupted run is `WHERE png IS NULL`.
--
--   INSERT INTO frame (name, w, h, cam_from)
--   SELECT format('orbit-%s', i), 480, 320,
--          v3(6.7 * cos(radians(i * 6)), 2.35, 6.7 * sin(radians(i * 6)))
--   FROM generate_series(0, 59) i;
--
--   SELECT render_frame(frame_id) FROM frame WHERE png IS NULL ORDER BY frame_id;
--
-- Camera motion costs nothing extra: it touches no geometry, so `tri` and the
-- BVH are untouched between frames and nothing is reindexed.
CREATE FUNCTION render_frame(p_frame_id int, p_verbose boolean DEFAULT false)
RETURNS int AS $$
DECLARE
  f  frame;
  t0 timestamptz := clock_timestamp();
BEGIN
  SELECT * INTO f FROM frame WHERE frame_id = p_frame_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'no frame with frame_id %', p_frame_id;
  END IF;

  PERFORM render(f.w, f.h, f.aa, f.maxdepth, f.exposure, f.cutoff, p_verbose,
                 f.cam_from, f.cam_at, f.cam_fov, f.refine);

  UPDATE frame
     SET png         = png_encode(f.w, f.h, png_scanlines('img')),
         rendered_at = t0,
         elapsed_ms  = round(extract(epoch FROM clock_timestamp() - t0) * 1000)
   WHERE frame_id = p_frame_id;

  RETURN p_frame_id;
END $$ LANGUAGE plpgsql;

CREATE FUNCTION render_frame(p_name text, p_verbose boolean DEFAULT false)
RETURNS int AS $$
DECLARE fid int;
BEGIN
  SELECT frame_id INTO fid FROM frame WHERE name = p_name;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'no frame named %', p_name;
  END IF;
  RETURN render_frame(fid, p_verbose);
END $$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Take one unrendered frame and render it, or return NULL if there are none.
--
-- This is the whole of the parallel driver's server side.  `frame` was already
-- a work queue -- `WHERE png IS NULL` is the backlog, and that is how an
-- interrupted sequence resumes -- so making it a *concurrent* queue needs only
-- the one clause SQL has had since 9.5.  FOR UPDATE takes a row lock that is
-- held until the transaction ends, which here is until the frame is traced and
-- stored; SKIP LOCKED steps over rows another session is already tracing
-- instead of waiting behind them.  N sessions calling this in a loop therefore
-- pull disjoint frames with no coordination between them, and a session that
-- dies mid-frame drops its lock and its uncommitted UPDATE together, putting
-- the frame straight back in the queue.
--
-- LIMIT after a locking clause reads like a race and is not one: the plan puts
-- LockRows below Limit, so the skipping happens first and the limit takes the
-- first row that was actually claimed.
--
-- Calling it from psql one statement at a time is deliberate -- each call is
-- its own transaction, so each frame commits as it finishes.  Wrapping the
-- loop in a DO block would hold every lock and every PNG until the last frame
-- was done, which is the opposite of what a resumable queue is for.
-- ---------------------------------------------------------------------------
CREATE FUNCTION render_next_frame(p_verbose boolean DEFAULT false)
RETURNS int AS $$
DECLARE fid int;
BEGIN
  SELECT frame_id INTO fid
    FROM frame
   WHERE png IS NULL
   ORDER BY frame_id
     FOR UPDATE SKIP LOCKED
   LIMIT 1;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN render_frame(fid, p_verbose);
END $$ LANGUAGE plpgsql;
